from __future__ import annotations

from ptsm.domain.topic_guidance import (
    FormatRecommendation,
    TopicDirection,
    TopicLane,
    TopicPack,
)


FENGKUANG_PACK = TopicPack(
    playbook_id="fengkuang_daily_post",
    default_account_id="acct-fk-local",
    default_image_style="note_card",
    guidance_message="这条发疯文学内容建议先从下面选一个可接龙方向，再进入生成。",
    lanes=(
        TopicLane(
            name="职场物件 / 替人发疯",
            default_scene="领导18:57发来一句在吗，工牌想替我发疯",
            default_content_angle="让一个具体物件替打工人说出没发出去的疯话。",
            default_saveable_tool="物件 / 疯话 / 体面翻译三栏",
            default_comment_prompt="你今天想让哪个物件替你发疯？",
            keywords=("工牌", "电脑", "键盘", "杯子", "领导", "工位", "物件"),
        ),
        TopicLane(
            name="高雅外壳 / 狼狈内核",
            default_scene="明明只是被临时加活，却想写成一碗丝瓜汤",
            default_content_angle="用体面词包装狼狈现场，让反差成为笑点。",
            default_saveable_tool="原句 / 高雅说法 / 实际意思",
            default_comment_prompt="你还有什么高雅外壳的狼狈句？",
            keywords=("高雅", "狼狈", "丝瓜汤", "体面", "翻译"),
        ),
        TopicLane(
            name="群聊未发送 / 评论区接龙",
            default_scene="群聊里那句没发出去的话，最后让评论区替我说了",
            default_content_angle="把没发出去的一句话变成评论区接龙入口。",
            default_saveable_tool="场景 / 没发出去的话 / 体面版本",
            default_comment_prompt="把你没发出去的那句话留在评论区。",
            keywords=("群聊", "没发", "回复", "接龙", "消息", "在吗"),
        ),
        TopicLane(
            name="体面人设 / 活人崩溃",
            default_scene="表面收到，实际灵魂已经从会议室离职",
            default_content_angle="表面维持体面，内核保留活人的荒诞反应。",
            default_saveable_tool="表面台词 / 内心字幕 / 今日缓冲词",
            default_comment_prompt="你今天哪一秒最像体面外壳裂开？",
            keywords=("体面", "收到", "会议", "崩溃", "活人", "下班"),
        ),
    ),
    directions=(
        TopicDirection(
            id="fk_work_object_vent",
            name="职场物件替人发疯",
            trend_signal="物件发疯 / 抽象力",
            viral_hook="评论区补一句",
            why_it_may_work="把情绪交给工牌、键盘、杯子这类具体物件，既有代入感，也方便评论区接力。",
            best_scenes=("领导临下班发在吗", "工牌像替身一样挂了一天", "电脑风扇比人先崩溃"),
            content_angle="不是人在发疯，是工牌终于替我把那句话说出来了。",
            saveable_tool="物件 / 它想说的话 / 体面翻译",
            comment_prompt="你今天想让哪个物件替你发疯？",
            avoid="不要拿心理疾病、医院、治疗或用药当笑点。",
            lane_affinity=("职场物件",),
            scene_keywords=("工牌", "键盘", "电脑", "杯子", "领导", "工位", "发疯"),
            base_priority=8,
        ),
        TopicDirection(
            id="fk_loofah_soup_reply",
            name="丝瓜汤式复盘",
            trend_signal="丝瓜汤 / 高雅外壳",
            viral_hook="可复制疯话",
            why_it_may_work="用高雅句式包住真实狼狈，反差强，也能让用户贡献自己的体面翻译。",
            best_scenes=("被安排临时需求", "一句收到背后有很多话", "想把崩溃写得很讲究"),
            content_angle="把不想干写成一碗温润的丝瓜汤，体面但不失真。",
            saveable_tool="原句 / 丝瓜汤说法 / 实际意思",
            comment_prompt="你还有哪句适合熬成丝瓜汤？",
            avoid="不要攻击具体个人，不要变成阴阳怪气人身攻击。",
            lane_affinity=("高雅外壳",),
            scene_keywords=("丝瓜汤", "高雅", "体面", "临时", "收到", "复盘"),
            base_priority=7,
        ),
        TopicDirection(
            id="fk_group_chat_unsent_line",
            name="群聊没发出去的话",
            trend_signal="打工人关系角色",
            viral_hook="接龙",
            why_it_may_work="未发送消息是高频场景，评论区天然会接自己的那一句。",
            best_scenes=("群聊里忍住没回", "领导发在吗", "同事让你帮忙兜底"),
            content_angle="最疯的不是发出去的话，是删掉以后还在脑子里加班的那句。",
            saveable_tool="场景 / 没发出去的话 / 体面版本",
            comment_prompt="把你没发出去的那句话交出来。",
            avoid="不要鼓励网暴、挂人或泄露真实聊天隐私。",
            lane_affinity=("群聊未发送",),
            scene_keywords=("群聊", "没发", "没发出去", "在吗", "消息", "回复", "领导"),
            base_priority=7,
        ),
        TopicDirection(
            id="fk_polite_shell_wild_core",
            name="体面外壳狼狈内核",
            trend_signal="高雅外壳 / 活人感",
            viral_hook="身份认领",
            why_it_may_work="体面与狼狈的反差容易被认领，也能保持发疯文学的分寸。",
            best_scenes=("表面说收到", "会后还在脑内骂骂咧咧", "下班路上突然想通又没想通"),
            content_angle="体面是外壳，活人才是内核。",
            saveable_tool="表面台词 / 内心字幕 / 今日缓冲词",
            comment_prompt="你今天是哪一种体面外壳？",
            avoid="不要把崩溃写成伤害自己或他人的行动建议。",
            lane_affinity=("体面人设", "高雅外壳"),
            scene_keywords=("体面", "收到", "狼狈", "活人", "崩溃", "下班"),
            base_priority=6,
        ),
        TopicDirection(
            id="fk_deadline_receipt_translation",
            name="临时需求：收到的体面翻译",
            trend_signal="DDL / 高雅外壳",
            viral_hook="可复制体面回复",
            why_it_may_work="临时加活和截止时间是高频打工人场景，体面翻译能让读者直接改成自己的版本。",
            best_scenes=("今晚突然多一个需求", "一句收到背后全是 DDL", "截止时间临时提前"),
            content_angle="所谓收到，有时只是把一整套崩溃先翻译成体面中文。",
            saveable_tool="真实反应 / 体面翻译 / 可发送版本",
            comment_prompt="你最近哪句收到最需要翻译？",
            avoid="不要教人硬刚具体个人，不泄露真实公司和聊天隐私。",
            lane_affinity=("高雅外壳", "体面人设"),
            scene_keywords=("临时", "加活", "需求", "截止", "今晚", "ddl", "deadline", "收到"),
            base_priority=6,
            diversity_key="reply-template",
        ),
        TopicDirection(
            id="fk_unsent_group_chat_aftertaste",
            name="群聊删掉以后，脑子还在加班",
            trend_signal="群聊未发送 / 活人感",
            viral_hook="评论区交没发出去的话",
            why_it_may_work="未发送消息和脑内加班都很具体，读者容易把自己的那句补到评论区。",
            best_scenes=("群聊里删掉一句话", "同事让你帮忙兜底", "脑子还在排练体面回复"),
            content_angle="最累的不是没发出去，是删掉以后它还在脑子里打卡。",
            saveable_tool="原话 / 删掉原因 / 体面替代句",
            comment_prompt="你删掉过哪句最想发的话？",
            avoid="不要挂人、泄露聊天记录或鼓励网暴。",
            lane_affinity=("群聊未发送", "体面人设"),
            scene_keywords=("群聊", "没发出去", "删掉", "同事", "兜底", "脑子", "加班", "帮忙"),
            base_priority=5,
            diversity_key="comment-chain",
        ),
    ),
)


HUMAN_ENRICHMENT_PACK = TopicPack(
    playbook_id="human_enrichment_daily_post",
    default_account_id="acct-enrichment-local",
    default_image_style="note_card",
    guidance_message="这条人类丰容内容建议先从下面选一个低成本变量方向，再进入生成。",
    lanes=(
        TopicLane(
            name="一平米角落 / 低成本变量",
            default_scene="把书桌角落改成十分钟适我主义手作位",
            default_content_angle="不是改造整个家，只给一个角落加一个下班信号。",
            default_saveable_tool="原本惯性 / 一个变量 / 今天能试的一步",
            default_comment_prompt="你先想丰容哪个角落？",
            keywords=("书桌", "角落", "工位", "床头", "玄关", "适我主义"),
        ),
        TopicLane(
            name="睡前下线 / 微仪式",
            default_scene="床头只放充电线，睡前总觉得没下线",
            default_content_angle="给睡前十分钟加一个可重复的结束信号。",
            default_saveable_tool="入口 / 下线动作 / 明天第一步",
            default_comment_prompt="你想先给哪个入口下线？",
            keywords=("床头", "睡前", "下线", "十分钟", "充电线"),
        ),
        TopicLane(
            name="通勤路线 / Colorwalk",
            default_scene="下班路上给自己一个找绿色的任务",
            default_content_angle="不换城市，只给通勤路线加一个感官变量。",
            default_saveable_tool="路线 / 颜色任务 / 拍到的一处细节",
            default_comment_prompt="你会给通勤加什么颜色任务？",
            keywords=("通勤", "路线", "colorwalk", "颜色", "下班路"),
        ),
        TopicLane(
            name="手作材料 / 心流平铺",
            default_scene="把手作材料摊开，先做十分钟就停",
            default_content_angle="材料平铺比成品更容易展示今天能开始的一步。",
            default_saveable_tool="材料 / 十分钟动作 / 停止点",
            default_comment_prompt="你最想摊开哪一种材料？",
            keywords=("手作", "材料", "心流", "平铺", "十分钟"),
        ),
    ),
    directions=(
        TopicDirection(
            id="enrichment_desk_corner_variable",
            name="一平米角落：书桌下班信号",
            trend_signal="适我主义 / 新独居",
            viral_hook="低成本 before/after",
            why_it_may_work="具体角落加三步清单容易收藏，也容易让评论区交作业。",
            best_scenes=("书桌太像工位", "床头只有充电线", "玄关一进门就很乱"),
            content_angle="不是改造整个家，只是给一个角落加一个下班信号。",
            saveable_tool="原本惯性 / 一个变量 / 今天能试的一步",
            comment_prompt="你先想丰容哪个角落？",
            avoid="不要写成购物清单，不要用 AI 图伪装真实改造。",
            format_recommendation=FormatRecommendation(
                format_archetype="provider_scene",
                cover_role="evidence_or_scene",
                body_shape="scene photo or generated scene / before friction / one low-cost variable / comment assignment",
                visual_evidence_need="high",
                avoid_format=("dense_text_poster", "fake_before_after"),
            ),
            lane_affinity=("一平米角落",),
            scene_keywords=("书桌", "角落", "工位", "适我主义", "低成本"),
            base_priority=8,
        ),
        TopicDirection(
            id="enrichment_bedside_shutdown_signal",
            name="床头下线信号",
            trend_signal="睡前十分钟",
            viral_hook="三步清单",
            why_it_may_work="睡前场景高频，三步下线动作比宏大自律更容易被保存。",
            best_scenes=("床头只有充电线", "睡前刷手机停不下来", "想让房间有结束感"),
            content_angle="丰容不是多买东西，是让身体知道今天可以结束了。",
            saveable_tool="关入口 / 留明天第一步 / 放一个低刺激物件",
            comment_prompt="你想给睡前加哪一个下线信号？",
            avoid="不要做助眠治疗承诺，不要把失眠简单归因于自控力。",
            format_recommendation=FormatRecommendation(
                format_archetype="provider_scene",
                cover_role="evidence_or_scene",
                body_shape="quiet bedside scene / shutdown signal / 3-step low-stimulus action",
                visual_evidence_need="high",
                avoid_format=("dense_text_poster", "medical_before_after"),
            ),
            lane_affinity=("睡前下线",),
            scene_keywords=("床头", "睡前", "下线", "充电线", "十分钟"),
            base_priority=7,
        ),
        TopicDirection(
            id="enrichment_route_colorwalk",
            name="通勤路线微变量",
            trend_signal="Colorwalk / 低成本行动",
            viral_hook="交作业",
            why_it_may_work="路线变量不需要购物，评论区可以用颜色任务交作业。",
            best_scenes=("每天同一条下班路", "周末不想远行", "想低成本找回一点新鲜感"),
            content_angle="不换城市，也能把今天的路线换一个观察方式。",
            saveable_tool="路线 / 颜色 / 一张细节照片",
            comment_prompt="你明天的通勤颜色任务是什么？",
            avoid="不要写成旅游攻略，也不要暗示危险拍摄或影响通行。",
            format_recommendation=FormatRecommendation(
                format_archetype="carousel",
                cover_role="evidence_or_scene",
                body_shape="route detail photo / color mission / 2-3 captured details / comment assignment",
                visual_evidence_need="high",
                avoid_format=("dense_text_poster", "stock_travel_guide"),
            ),
            lane_affinity=("通勤路线",),
            scene_keywords=("通勤", "路线", "colorwalk", "颜色", "下班路"),
            base_priority=6,
        ),
        TopicDirection(
            id="enrichment_handmade_material_flow",
            name="手作材料平铺",
            trend_signal="手作心流",
            viral_hook="过程轮播",
            why_it_may_work="材料和过程比完美成品更有真实感，也适合轮播拆步骤。",
            best_scenes=("想做手作但迟迟没开始", "材料堆在角落", "只想做十分钟"),
            content_angle="今天不追求完成，只把材料摊开，让开始变小。",
            saveable_tool="材料 / 十分钟动作 / 停止点",
            comment_prompt="你最想摊开哪一种材料？",
            avoid="不要写成昂贵工具种草，不要把失败手作包装成完美教程。",
            format_recommendation=FormatRecommendation(
                format_archetype="carousel",
                cover_role="evidence_or_scene",
                body_shape="material spread / 10-minute process / stop point / imperfect result",
                visual_evidence_need="high",
                avoid_format=("dense_text_poster", "perfect_tutorial_poster"),
            ),
            lane_affinity=("手作材料",),
            scene_keywords=("手作", "材料", "心流", "平铺", "十分钟"),
            base_priority=6,
        ),
        TopicDirection(
            id="enrichment_commute_color_mission",
            name="通勤 Colorwalk：给下班路一个颜色任务",
            trend_signal="Colorwalk / 低成本变量",
            viral_hook="评论区交作业",
            why_it_may_work="通勤路线不用购物也能马上执行，颜色任务让读者有明确参与方式。",
            best_scenes=("下班路上找一种颜色", "每天走同一条路线", "不想远行但想换一点感官"),
            content_angle="不用换城市，先把今天的下班路换成一个观察任务。",
            saveable_tool="路线 / 颜色任务 / 拍到的一处细节",
            comment_prompt="你明天想找哪一种颜色？",
            avoid="不要鼓励危险拍摄，不把普通通勤包装成旅游攻略。",
            format_recommendation=FormatRecommendation(
                format_archetype="carousel",
                cover_role="evidence_or_scene",
                body_shape="color detail cover / route task / one captured detail / comment assignment",
                visual_evidence_need="high",
                avoid_format=("dense_text_poster", "stock_travel_guide"),
            ),
            lane_affinity=("通勤路线",),
            scene_keywords=("通勤", "下班路", "绿色", "colorwalk", "颜色", "路线", "拍照"),
            base_priority=5,
            diversity_key="outdoor-mission",
        ),
        TopicDirection(
            id="enrichment_bag_rescue_kit",
            name="包里救援角：给外出留一个小缓冲",
            trend_signal="适我主义 / 微型安全感",
            viral_hook="低成本清单",
            why_it_may_work="包内小物比改造房间更轻，适合通勤、上课、出门前这类高频场景。",
            best_scenes=("通勤包太乱", "出门总觉得少点东西", "想准备一个不消费的缓冲角"),
            content_angle="人类丰容有时不是改房间，是给包里留一个能接住自己的角落。",
            saveable_tool="必带 / 可缓冲 / 今天先减掉的一样",
            comment_prompt="你的包里最想先留哪个缓冲小物？",
            avoid="不要变成购物清单，不制造精致生活焦虑。",
            format_recommendation=FormatRecommendation(
                format_archetype="provider_scene",
                cover_role="evidence_or_scene",
                body_shape="bag corner scene / keep-remove-buffer checklist / comment assignment",
                visual_evidence_need="high",
                avoid_format=("dense_text_poster", "shopping_flatlay"),
            ),
            lane_affinity=("一平米角落", "通勤路线"),
            scene_keywords=("包", "通勤", "外出", "小物", "缓冲", "出门", "安全感"),
            base_priority=4,
            diversity_key="micro-kit",
        ),
    ),
)


CLASSIC_POETRY_PACK = TopicPack(
    playbook_id="classic_poetry_quote_post",
    default_account_id="acct-classic-poetry-local",
    default_image_style="note_card",
    guidance_message="这条古诗词金句内容建议先从下面选一个经典诗句入口，再进入生成。",
    lanes=(
        TopicLane(
            name="唐诗金句 / 低谷打气",
            default_scene="读到李白长风破浪会有时，想写给低谷里的自己",
            default_content_angle="用一句确定的唐诗金句，接住今天还没看到结果的低谷感。",
            default_saveable_tool="眼前低谷 / 这一句 / 今天还能做的一步",
            default_comment_prompt="你会把哪一句古诗词留给低谷里的自己？",
            keywords=("古诗词", "金句", "经典诗句", "诗词金句", "切口", "方向", "主题", "李白", "长风破浪", "行路难", "低谷", "打气", "自己"),
        ),
        TopicLane(
            name="宋词清醒 / 情绪安放",
            default_scene="深夜读到李清照，想写一句能安放情绪的词",
            default_content_angle="把宋词里的细腻情绪写成今天能存下来的清醒小纸条。",
            default_saveable_tool="情绪现场 / 这一句词 / 我先怎么照顾自己",
            default_comment_prompt="哪一句词最像你最近的心情？",
            keywords=("李清照", "宋词", "词", "情绪", "深夜", "清醒", "人比黄花瘦", "声声慢", "安放"),
        ),
        TopicLane(
            name="月亮乡愁 / 远方想念",
            default_scene="下班路上看到月亮，想写一句古诗词金句给没联系很久的人",
            default_content_angle="用月亮和远方把想念写轻一点，不把情绪写成煽情模板。",
            default_saveable_tool="月亮场景 / 想念的人 / 可以留下的一句",
            default_comment_prompt="你会把今晚的月亮寄给谁？",
            keywords=("月亮", "明月", "乡愁", "想念", "思念", "远方", "李白", "张九龄", "但愿人长久", "没联系"),
        ),
        TopicLane(
            name="山水松弛 / 下班留白",
            default_scene="想写王维山水诗，给下班后的自己一点松弛",
            default_content_angle="用山水诗里的留白感，把紧绷的一天慢慢放下来。",
            default_saveable_tool="紧绷现场 / 一句山水诗 / 今晚留白动作",
            default_comment_prompt="你最想把哪一刻交给山水诗？",
            keywords=("王维", "山水", "空山", "松弛", "下班", "留白", "鸟鸣涧", "山居秋暝"),
        ),
        TopicLane(
            name="杜甫现实感 / 普通日子",
            default_scene="想用杜甫写普通人今天仍然要把日子过下去",
            default_content_angle="把杜甫的现实感写成普通人仍然愿意照看生活的一点力气。",
            default_saveable_tool="现实压力 / 这一句 / 今天先守住什么",
            default_comment_prompt="哪一句诗最像你今天的现实感？",
            keywords=("杜甫", "现实", "普通人", "日子", "生活", "压力", "茅屋", "春望"),
        ),
        TopicLane(
            name="节气四季 / 小动作",
            default_scene="一个节气里只做一件小事，再配一句古诗词",
            default_content_angle="把节气从知识点写成今天可以慢慢做的一件小事。",
            default_saveable_tool="节气 / 一件小事 / 一句诗",
            default_comment_prompt="这个节气你想把哪一句诗存下来？",
            keywords=("节气", "四季", "春天", "夏天", "秋天", "冬天", "季节", "小动作", "仪式"),
        ),
        TopicLane(
            name="苏轼定风波 / 坏天气重读",
            default_scene="今天过得很狼狈，想借定风波重新看一眼",
            default_content_angle="把苏轼作为古诗词金句里的一个方向，不把狼狈美化，只给它一个可放下的句子。",
            default_saveable_tool="狼狈场景 / 词句 / 放下一步",
            default_comment_prompt="你今天最想把哪点狼狈写进一句词？",
            keywords=("苏轼", "定风波", "风雨", "狼狈", "坏天气", "放下", "莫听穿林打叶声"),
        ),
    ),
    directions=(
        TopicDirection(
            id="classic_tang_resilience_quote",
            name="李白这一句：低谷先别判输赢",
            trend_signal="唐诗金句 / 低谷打气",
            viral_hook="一句可截图重读",
            why_it_may_work="长风破浪会有时本来就有强传播记忆点，落到低谷现场后更容易被保存和转发。",
            best_scenes=("考研或工作低谷", "结果还没出来时", "想给自己留一句不鸡血的打气"),
            content_angle="不是喊你立刻赢，而是提醒你：看不见风的时候，也可以先把船稳住。",
            saveable_tool="眼前低谷 / 长风破浪会有时 / 今天还能做的一步",
            comment_prompt="你会把哪一句古诗词留给低谷里的自己？",
            avoid="不要把古诗词写成成功学鸡汤，不要伪造李白原句或篇名。",
            lane_affinity=("唐诗金句",),
            scene_keywords=("古诗词", "金句", "诗词金句", "经典诗句", "切口", "方向", "不同", "几个", "多个", "李白", "长风破浪", "行路难", "低谷", "打气", "自己"),
            base_priority=8,
            diversity_key="resilience-quote",
        ),
        TopicDirection(
            id="classic_song_emotion_quote",
            name="李清照这一句：情绪可以慢慢安放",
            trend_signal="宋词清醒 / 深夜情绪",
            viral_hook="情绪小纸条",
            why_it_may_work="李清照的词适合承接深夜、脆弱和自我照看，比泛泛治愈更有文本抓手。",
            best_scenes=("深夜情绪上来", "很想说但不知道怎么说", "读到一句词突然被照见"),
            content_angle="这类词不是教人难过，而是允许你先承认：我今天确实轻不起来。",
            saveable_tool="情绪现场 / 这一句词 / 我先怎么照顾自己",
            comment_prompt="哪一句词最像你最近的心情？",
            avoid="不要把李清照写成苦情标签，不要伪造原词。",
            lane_affinity=("宋词清醒",),
            scene_keywords=("古诗词", "金句", "李清照", "宋词", "深夜", "情绪", "人比黄花瘦", "声声慢", "清醒", "安放"),
            base_priority=8,
            diversity_key="song-emotion",
        ),
        TopicDirection(
            id="classic_moon_longing_quote",
            name="月亮这一句：把想念说轻一点",
            trend_signal="月亮诗句 / 远方想念",
            viral_hook="把月亮寄给谁",
            why_it_may_work="月亮是古诗词里最高频的情绪入口，也天然适合评论区分享远方的人。",
            best_scenes=("下班路上看到月亮", "想念很久没联系的人", "中秋或异地时刻"),
            content_angle="月亮不是只负责孤独，也可以负责把惦记说得轻一点。",
            saveable_tool="月亮场景 / 想念的人 / 可以留下的一句",
            comment_prompt="你会把今晚的月亮寄给谁？",
            avoid="不要把亲情友情写成煽情模板，不要堆砌整段诗词。",
            lane_affinity=("月亮乡愁",),
            scene_keywords=("古诗词", "金句", "月亮", "明月", "乡愁", "想念", "思念", "远方", "李白", "张九龄", "但愿人长久", "没联系"),
            base_priority=8,
            diversity_key="moon-longing",
        ),
        TopicDirection(
            id="classic_landscape_ease_quote",
            name="王维这一句：给紧绷的一天留白",
            trend_signal="山水诗 / 松弛感",
            viral_hook="下班留白卡",
            why_it_may_work="王维山水诗能把松弛感落到具体画面，不需要写成空泛治愈。",
            best_scenes=("下班后很紧绷", "想给晚上留一点空白", "需要一张低密度保存卡"),
            content_angle="有些诗不是让你逃进山里，而是提醒你在今天也能给自己留一小块安静。",
            saveable_tool="紧绷现场 / 一句山水诗 / 今晚留白动作",
            comment_prompt="你最想把哪一刻交给山水诗？",
            avoid="不要把山水诗写成旅游种草或景点导览。",
            lane_affinity=("山水松弛",),
            scene_keywords=("古诗词", "金句", "王维", "山水", "空山", "松弛", "下班", "留白", "鸟鸣涧", "山居秋暝"),
            base_priority=8,
            diversity_key="landscape-ease",
        ),
        TopicDirection(
            id="classic_dufu_real_life_quote",
            name="杜甫这一句：普通日子也值得守住",
            trend_signal="杜甫 / 现实感",
            viral_hook="现实三问",
            why_it_may_work="杜甫适合把古诗词从漂亮句子拉回普通人的现实生活和可保存判断。",
            best_scenes=("普通日子很难但还要过", "被现实压住时", "想写不鸡血的坚持"),
            content_angle="现实感不是丧，是看见难处以后仍然愿意守住一点生活。",
            saveable_tool="现实压力 / 这一句 / 今天先守住什么",
            comment_prompt="哪一句诗最像你今天的现实感？",
            avoid="不要把苦难浪漫化，不要用诗替代现实帮助。",
            lane_affinity=("杜甫现实感",),
            scene_keywords=("杜甫", "现实", "普通人", "日子", "生活", "压力", "茅屋", "春望"),
            base_priority=7,
            diversity_key="real-life",
        ),
        TopicDirection(
            id="classic_season_micro_ritual",
            name="节气里的小动作",
            trend_signal="节气 / 非遗",
            viral_hook="可保存小纸条",
            why_it_may_work="节气话题有搜索入口，小动作能避免百科腔。",
            best_scenes=("立夏想做一件小事", "下雨天泡一杯茶", "季节变化时想慢一点"),
            content_angle="节气不是知识点，是今天可以慢慢做的一件小事，再配一句确定的诗。",
            saveable_tool="节气 / 一件小事 / 一句诗",
            comment_prompt="这个节气你想把哪一句诗存下来？",
            avoid="不要伪造民俗出处，不要把节气写成空泛鸡汤。",
            lane_affinity=("节气四季",),
            scene_keywords=("节气", "四季", "季节", "小动作", "仪式", "春天", "秋天"),
            base_priority=6,
            diversity_key="season-ritual",
        ),
        TopicDirection(
            id="classic_sushi_dingfengbo_optional",
            name="苏轼定风波：狼狈不是失败证据",
            trend_signal="苏轼 / 定风波",
            viral_hook="轻量重读",
            why_it_may_work="保留苏轼作为古诗词金句的一个强分支，但只在定风波、风雨、狼狈等场景命中。",
            best_scenes=("今天很狼狈", "遇到坏天气", "读到定风波想放过自己"),
            content_angle="不是把狼狈变美，而是给它一个可以暂时放下的句子。",
            saveable_tool="狼狈场景 / 词句 / 放下一步",
            comment_prompt="你今天最想把哪点狼狈写进一句词？",
            avoid="不要用诗词否定现实困难，也不要写成万能治愈。",
            lane_affinity=("苏轼定风波",),
            scene_keywords=("苏轼", "定风波", "风雨", "狼狈", "坏天气", "莫听穿林打叶声"),
            base_priority=6,
            diversity_key="reframe-card",
        ),
    ),
)


WUXIA_CHARACTER_PACK = TopicPack(
    playbook_id="wuxia_character_post",
    default_account_id="acct-wuxia-local",
    default_image_style="note_card",
    guidance_message="这条武侠人物评述建议先从下面选一个当代生活入口，再进入生成。",
    lanes=(
        TopicLane(
            name="老款人格 / 角色认领",
            default_scene="想用令狐冲写一种当代职场里的自由人格",
            default_content_angle="把武侠人物从剧情简介里拉回当代人的性格认领。",
            default_saveable_tool="人物 / 当代处境 / 一句可截图判断",
            default_comment_prompt="你最像哪一种老款人格？",
            keywords=("令狐冲", "郭靖", "黄蓉", "杨过", "小龙女", "老款人格", "自由"),
        ),
        TopicLane(
            name="当代职场 / 江湖镜像",
            default_scene="用黄蓉写一个今天也能看懂的职场判断",
            default_content_angle="把门派、江湖和人情写成今天的组织关系和能力选择。",
            default_saveable_tool="江湖处境 / 职场镜像 / 今日判断",
            default_comment_prompt="你觉得哪个武侠人物最像今天的职场人？",
            keywords=("职场", "领导", "同事", "组织", "能力", "CEO", "黄蓉"),
        ),
        TopicLane(
            name="主体性 / 边界选择",
            default_scene="想写小龙女不是冷淡，而是在守住自己的选择",
            default_content_angle="用人物处境讨论主体性和边界，不把复杂人物压扁成标签。",
            default_saveable_tool="人物选择 / 代价 / 今天能借的一句话",
            default_comment_prompt="你最想替哪个人物说一句公道话？",
            keywords=("主体性", "边界", "选择", "小龙女", "黄蓉", "郭靖", "杨过"),
        ),
        TopicLane(
            name="人情债 / 关系困局",
            default_scene="用李寻欢写一种很会还人情、也很会为难自己的关系",
            default_content_angle="把江湖人情债翻译成当代关系里的亏欠、体面和自我消耗。",
            default_saveable_tool="人情债 / 真实选择 / 评论区问题",
            default_comment_prompt="你最想聊哪一种江湖人情债？",
            keywords=("人情", "亏欠", "关系", "李寻欢", "古龙", "体面", "自我消耗"),
        ),
    ),
    directions=(
        TopicDirection(
            id="wuxia_old_school_personality",
            name="老款人格：今天你像哪位江湖人",
            trend_signal="老款人格 / 角色认领",
            viral_hook="评论区认领",
            why_it_may_work="武侠人物自带记忆点，老款人格能让读者把角色复杂性和自己的当代处境连起来。",
            best_scenes=("令狐冲的自由感", "郭靖的笨拙可靠", "黄蓉的聪明和责任"),
            content_angle="不是把人物贴标签，而是从一个选择里看见今天还在发生的人格困境。",
            saveable_tool="人物 / 当代处境 / 一句可截图判断",
            comment_prompt="你今天最像哪位江湖人？",
            avoid="不要写成百科词条，不要只复述剧情。",
            lane_affinity=("老款人格", "角色认领"),
            scene_keywords=("令狐冲", "郭靖", "黄蓉", "杨过", "小龙女", "老款人格", "自由"),
            base_priority=8,
        ),
        TopicDirection(
            id="wuxia_workplace_mirror",
            name="武侠人物照进当代职场",
            trend_signal="职场镜像 / 文化力",
            viral_hook="当代人代入",
            why_it_may_work="把江湖处境翻译成职场关系，既有观点，也能降低古典内容的进入门槛。",
            best_scenes=("黄蓉像被低估的组织者", "令狐冲不适合被 KPI 驯化", "郭靖的慢就是护城河"),
            content_angle="江湖不是离我们很远，很多门派关系只是换了一个办公室名字。",
            saveable_tool="江湖处境 / 职场镜像 / 今日判断",
            comment_prompt="你觉得谁最像今天的职场人？",
            avoid="不要过度现代化硬套，不要把人物压扁成职场标签。",
            lane_affinity=("当代职场",),
            scene_keywords=("职场", "工位", "领导", "同事", "组织", "黄蓉", "CEO", "KPI"),
            base_priority=7,
        ),
        TopicDirection(
            id="wuxia_boundary_choice",
            name="主体性：人物真正守住的那条边界",
            trend_signal="主体性 / 边界感",
            viral_hook="替人物说句公道话",
            why_it_may_work="边界和主体性是当代高共鸣词，但用人物选择承接，能避免空泛鸡汤。",
            best_scenes=("小龙女的冷淡被误读", "黄蓉的聪明不只是讨好", "杨过的选择需要代价"),
            content_angle="真正动人的不是他做了正确选择，而是他承担了选择的代价。",
            saveable_tool="人物选择 / 代价 / 今天能借的一句话",
            comment_prompt="你最想替哪个人物说一句公道话？",
            avoid="不要把复杂关系写成单一价值评判。",
            lane_affinity=("主体性", "边界"),
            scene_keywords=("主体性", "边界", "选择", "小龙女", "黄蓉", "杨过", "代价"),
            base_priority=7,
        ),
        TopicDirection(
            id="wuxia_relationship_debt",
            name="江湖人情债：体面背后的自我消耗",
            trend_signal="关系压力 / 人情债",
            viral_hook="评论区交一个关系",
            why_it_may_work="人情债能把武侠人物的义气、亏欠和牺牲转成现实关系讨论，评论区容易有故事。",
            best_scenes=("李寻欢的体面让自己受伤", "郭靖背着很多人的期待", "杨过在亏欠里寻找自己"),
            content_angle="很多江湖困局，今天换个名字叫不好意思拒绝。",
            saveable_tool="人情债 / 真实选择 / 评论区问题",
            comment_prompt="你最想聊哪一种江湖人情债？",
            avoid="不要鼓励站队拉踩，也不要把人物写成单纯受害者。",
            lane_affinity=("人情债", "关系困局"),
            scene_keywords=("人情", "亏欠", "关系", "李寻欢", "古龙", "体面", "拒绝"),
            base_priority=6,
        ),
        TopicDirection(
            id="wuxia_guojing_slow_growth",
            name="郭靖式慢成长：笨拙但可靠",
            trend_signal="老款人格 / 反速成",
            viral_hook="评论区认领慢热人格",
            why_it_may_work="郭靖能承接当代人的反速成焦虑，把笨拙写成一种稳定的长期主义。",
            best_scenes=("觉得自己学得慢", "不擅长表达但一直在做事", "被快节奏比较压住"),
            content_angle="郭靖最动人的不是开挂，而是慢慢长出来的可靠。",
            saveable_tool="人物处境 / 慢的代价 / 今天能借的一句话",
            comment_prompt="你身边有这种慢慢可靠起来的人吗？",
            avoid="不要把人物写成励志模板，不贬低聪明型角色。",
            lane_affinity=("老款人格", "主体性"),
            scene_keywords=("郭靖", "慢", "笨拙", "可靠", "成长", "长期主义", "反速成"),
            base_priority=6,
            diversity_key="character-growth",
        ),
        TopicDirection(
            id="wuxia_linghu_not_kpi",
            name="令狐冲不适合被 KPI 驯化",
            trend_signal="自由人格 / 职场镜像",
            viral_hook="一句可截图判断",
            why_it_may_work="令狐冲和当代职场有天然反差，能让读者讨论自由、组织和边界。",
            best_scenes=("不适合强流程的人", "职场里还想保留一点自由", "被 KPI 驯化得很累"),
            content_angle="有些人的能力不是没有边界，而是不该被同一种表格解释完。",
            saveable_tool="人物 / 职场镜像 / 一句判断",
            comment_prompt="哪个武侠人物最不适合被 KPI 管住？",
            avoid="不要把自由写成不负责任，不硬套现代管理术语。",
            lane_affinity=("当代职场", "老款人格"),
            scene_keywords=("令狐冲", "自由", "职场", "KPI", "流程", "组织", "驯化"),
            base_priority=5,
            diversity_key="workplace-mirror",
        ),
    ),
)


AI_TECH_PACK = TopicPack(
    playbook_id="ai_tech_daily_post",
    default_account_id="acct-ai-tech-local",
    default_image_style="note_card",
    guidance_message="AI 科技内容先选证据模式，再选方向；热点本身不是正文事实。",
    lanes=(
        TopicLane(
            name="模型更新 / 3 秒人话",
            default_scene="Google 发布 Gemini 3，想写普通人能懂的 AI 工具变化",
            default_content_angle="用核验事实做一条短快讯，或把单项更新翻成谁要关注、谁能等等。",
            default_saveable_tool="已核验事实 / 受众边界",
            default_comment_prompt="你所在的任务场景，会用到这项变化吗？",
            keywords=("模型", "Gemini", "ChatGPT", "Claude", "发布", "升级", "更新", "大模型"),
        ),
        TopicLane(
            name="工作流 / 普通人实用",
            default_scene="想写一个 AI 帮普通打工人省下重复劳动的工作流",
            default_content_angle="只写一次已记录的任务测试：输入是什么、输出怎样、哪里没跑通。",
            default_saveable_tool="任务 / 输入 / 观察结果 / 局限",
            default_comment_prompt="你会拿哪个低风险任务做一次自己的复盘？",
            keywords=("工作流", "效率", "办公", "打工人", "工具", "自动化", "文档"),
        ),
        TopicLane(
            name="工具选择 / 避坑判断",
            default_scene="想比较两个 AI 工具，帮读者判断该不该换",
            default_content_angle="先把产品差异翻成具体事实，再说明谁该关心、谁可以继续观望。",
            default_saveable_tool="已核验事实 / 谁该关注 / 谁可以等等",
            default_comment_prompt="你卡在产品能力、权限，还是接入成本？",
            keywords=("工具", "对比", "选择", "避坑", "适合", "不适合", "换工具"),
        ),
        TopicLane(
            name="提示词构建 / 好用 prompt",
            default_scene="想复盘一次让 AI 先问清楚再输出的 prompt 测试",
            default_content_angle="提示词只作为一次实测的输入；记录追问、输出和局限，不提供通用模板。",
            default_saveable_tool="测试任务 / 输入摘要 / 观察结果 / 局限",
            default_comment_prompt="如果你也测过同类任务，最容易卡在哪一步？",
            keywords=(
                "prompt",
                "提示词",
                "提问",
                "追问",
                "输出格式",
                "背景",
                "反例",
                "指令",
                "问清楚",
            ),
            default_image_style="iphone_notes",
        ),
        TopicLane(
            name="普通人影响 / 边界感",
            default_scene="想写 AI 新功能对普通人的影响，但不夸张预测",
            default_content_angle="只根据已核验事实说明影响范围和等待边界，不做泛泛预测。",
            default_saveable_tool="事实 / 谁该关注 / 谁可以等等",
            default_comment_prompt="这项变化会影响你的哪一个具体任务？",
            keywords=("普通人", "影响", "学习", "内容生产", "边界", "担心", "趋势"),
        ),
    ),
    directions=(
        TopicDirection(
            id="ai_news_three_updates_brief",
            name="AI 今日 3-5 条更新速览",
            content_mode="news_brief",
            trend_signal="AI 科技热点 / 多条核验更新",
            viral_hook="不用刷一堆发布页，先看三条",
            why_it_may_work="把同一时段的三到五条独立更新压成短卡，读者可以快速判断今天需要跟进哪一条。",
            best_scenes=("同一天出现多条模型或产品更新", "需要快速扫完 AI 科技动态", "想把热点整理成事实卡"),
            content_angle="每条只保留一个标签和已核验事实；三到五条独立事件并列，不延伸成主观体验。",
            saveable_tool="第 1-5 条：事件标签 / 已核验事实",
            comment_prompt="哪一条已经落到你的具体任务里？",
            avoid="不要把单一热点拆成三条，不写实测口吻、未核验性能判断、原始标题或来源信息。",
            format_recommendation=FormatRecommendation(
                format_archetype="carousel",
                cover_role="cover_hook",
                body_shape="3-5 independent update cards / one verified fact per card",
                visual_evidence_need="low",
                avoid_format=("dense_text_poster", "single-item-opinion"),
            ),
            lane_affinity=("模型更新", "3 秒"),
            scene_keywords=("快讯", "速览", "热点", "今天", "多条", "更新", "发布"),
            base_priority=9,
            diversity_key="news-brief-roundup",
        ),
        TopicDirection(
            id="ai_news_product_team_developer_brief",
            name="产品、开发者、团队：三条 AI 快讯",
            content_mode="news_brief",
            trend_signal="产品变化 / 开发者工具 / 团队能力",
            viral_hook="今天的变化，分成三张卡就够",
            why_it_may_work="按产品、开发者、团队三个读者常遇到的入口排列独立事件，比一篇长通稿更容易扫读。",
            best_scenes=("产品、开发者工具和团队功能同步更新", "读者关心接入与协作变化", "需要固定栏目式快讯"),
            content_angle="用三到五条不同事件做短快讯；每张卡只写证据文件里的标签与事实。",
            saveable_tool="产品 / 开发者 / 团队：各一条已核验事实",
            comment_prompt="你更需要产品、开发者，还是团队协作这一类变化？",
            avoid="不要把趋势热度当作事实，不补充未经记录的影响、体验或推荐。",
            format_recommendation=FormatRecommendation(
                format_archetype="carousel",
                cover_role="cover_hook",
                body_shape="3-5 evidence cards grouped by reader task / one fact each",
                visual_evidence_need="low",
                avoid_format=("dense_text_poster", "press-release-layout"),
            ),
            lane_affinity=("模型更新", "工具选择"),
            scene_keywords=("产品", "开发者", "团队", "控制台", "协作", "快讯", "更新"),
            base_priority=7,
            diversity_key="news-brief-reader-entry",
        ),
        TopicDirection(
            id="ai_model_update_plain_language",
            name="模型更新：3 秒讲清这次变了什么",
            content_mode="fact_translation",
            trend_signal="大模型更新 / 科技热点",
            viral_hook="这次更新，不是所有人都要追",
            why_it_may_work="模型更新容易信息过载；两条已核验事实加上“谁该关心、谁可等等”比泛泛感想更能帮助决策。",
            best_scenes=("新模型发布", "功能升级", "多模态能力变化"),
            content_angle="围绕一个明确更新，逐字保留至少两条已核验事实，再给出证据文件中的受众边界。",
            saveable_tool="主题 / 两条已核验事实 / 谁该关注 / 谁可以等等",
            comment_prompt="你的任务属于需要关注，还是可以等等？",
            avoid="不要写成发布会通稿，不编造体验、性能对比、投资建议或确定性预测。",
            format_recommendation=FormatRecommendation(
                format_archetype="note_card",
                cover_role="cover_hook",
                body_shape="one topic / 2 verified facts / who should care / who can wait",
                visual_evidence_need="low",
                avoid_format=("dense_text_poster", "parameter-comparison-poster"),
            ),
            lane_affinity=("模型更新", "3 秒"),
            scene_keywords=("模型", "Gemini", "ChatGPT", "Claude", "发布", "升级", "更新", "大模型"),
            base_priority=8,
        ),
        TopicDirection(
            id="ai_prompt_context_card",
            name="提示词实测：先补背景，输出有没有变",
            content_mode="hands_on",
            trend_signal="AI 提问 / 已记录任务测试",
            viral_hook="同一任务，补背景后的输出复盘",
            why_it_may_work="把提示词当作一次已记录测试的输入，展示任务、输入摘要、实际输出和局限，比万能模板更可信。",
            best_scenes=("让 AI 写文案总跑偏后的复盘", "记录一次先补背景再输出的测试", "比较同一任务的输入与结果"),
            content_angle="只复盘证据文件中那一次测试：产品、版本、日期、任务、输入摘要、观察结果和局限必须完整出现。",
            saveable_tool="测试任务 / 输入摘要 / 实际输出 / 局限",
            comment_prompt="同类任务里，你会先记录哪一个失败点？",
            avoid="不要提供通用可复制 prompt，不把单次结果写成稳定结论，不展示隐私或公司材料。",
            format_recommendation=FormatRecommendation(
                format_archetype="note_card",
                cover_role="evidence_or_scene",
                body_shape="test record / input summary / observed output / limitation",
                visual_evidence_need="high",
                avoid_format=("dense_text_poster", "copyable_prompt_block", "tool_hype_poster"),
            ),
            lane_affinity=("提示词构建", "好用 prompt"),
            scene_keywords=(
                "prompt",
                "提示词",
                "提问",
                "输出格式",
                "背景",
                "反例",
                "问清楚",
                "普通人",
                "小红书",
                "写好",
            ),
            base_priority=9,
            diversity_key="prompt-card",
        ),
        TopicDirection(
            id="ai_prompt_clarifying_questions",
            name="提示词实测：先追问，再开始输出",
            content_mode="hands_on",
            trend_signal="AI 工作流 / 追问式测试记录",
            viral_hook="先追问这一步，实际输出怎么变",
            why_it_may_work="追问能否减少返工必须由一次可复现任务证明；完整记录比一条泛化指令更容易判断是否值得复做。",
            best_scenes=("需求还没想清楚时的测试", "让 AI 写方案总太泛后的复盘", "记录追问对输出的实际影响"),
            content_angle="展示该次测试的产品与版本、日期、任务、输入摘要、观察输出和局限；不把流程变成万能方法。",
            saveable_tool="产品版本 / 测试任务 / 输入摘要 / 观察结果 / 局限",
            comment_prompt="你的测试记录里，最需要保留的是追问、输出，还是局限？",
            avoid="不要把追问包装成专家诊断，不替用户编造背景、隐私细节或未记录结果。",
            format_recommendation=FormatRecommendation(
                format_archetype="note_card",
                cover_role="evidence_or_scene",
                body_shape="dated test record / task and input / observed output / limitation",
                visual_evidence_need="high",
                avoid_format=("dense_text_poster", "copyable_prompt_block"),
            ),
            lane_affinity=("提示词构建", "工作流"),
            scene_keywords=("追问", "问清楚", "先问", "问题", "输出", "跑偏", "返工"),
            base_priority=8,
            diversity_key="prompt-clarifier",
        ),
        TopicDirection(
            id="ai_prompt_failure_replay",
            name="提示词复盘：失败输出别急着删",
            content_mode="hands_on",
            trend_signal="AI 使用反馈 / 失败测试复盘",
            viral_hook="一次没跑通的输出，怎么记录才有用",
            why_it_may_work="失败输出只有放回具体任务、输入和日期里才可解释；把局限一并给出，读者才不会误解成通用结论。",
            best_scenes=("AI 写得太官腔的一次测试", "输出格式不符合任务要求", "已记录失败输出与复盘结果"),
            content_angle="保留该次测试的输入摘要、观察输出和局限，说明产品、版本和日期；不展示完整原 prompt 或私密材料。",
            saveable_tool="测试任务 / 输入摘要 / 观察输出 / 局限",
            comment_prompt="复盘失败输出时，哪一项记录最容易漏掉？",
            avoid="不要展示隐私材料、公司机密、完整对话或让读者粘贴敏感输入。",
            format_recommendation=FormatRecommendation(
                format_archetype="note_card",
                cover_role="evidence_or_scene",
                body_shape="dated failed-test record / input summary / observed output / limitation",
                visual_evidence_need="high",
                avoid_format=("dense_text_poster", "full-chat-transcript"),
            ),
            lane_affinity=("提示词构建", "工具选择"),
            scene_keywords=("失败", "反例", "改写", "官腔", "格式", "重写", "失败输出"),
            base_priority=7,
            diversity_key="prompt-replay",
        ),
        TopicDirection(
            id="ai_workflow_real_use",
            name="AI 工作流实测：一个重复步骤怎么跑",
            content_mode="hands_on",
            trend_signal="AI 工作流 / 单任务测试",
            viral_hook="只复盘一个重复步骤，结果和局限都写",
            why_it_may_work="一个完整的单任务记录比“AI 能省事”的泛泛推荐更容易让读者判断自己的任务是否相近。",
            best_scenes=("整理会议纪要的一次测试", "把资料变成大纲的一次测试", "批量改写文案的一次测试"),
            content_angle="围绕单一任务完整呈现产品、版本、日期、输入摘要、观察输出和局限，不把单次结果夸成效率承诺。",
            saveable_tool="任务 / 输入摘要 / 观察输出 / 人工仍需核对的局限",
            comment_prompt="你的重复任务里，哪一项最适合先做一次可复现测试？",
            avoid="不要承诺效率翻倍，不把工具写成万能替身，也不隐藏人工核对环节。",
            format_recommendation=FormatRecommendation(
                format_archetype="carousel",
                cover_role="evidence_or_scene",
                body_shape="one task / dated test details / observed output / limitation",
                visual_evidence_need="high",
                avoid_format=("dense_text_poster", "before-after-performance-claim"),
            ),
            lane_affinity=("工作流",),
            scene_keywords=("工作流", "效率", "办公", "打工人", "工具", "自动化", "文档"),
            base_priority=7,
        ),
        TopicDirection(
            id="ai_tool_comparison_decision",
            name="AI 工具变化：谁该看，谁先等等",
            content_mode="fact_translation",
            trend_signal="工具对比 / 已核验产品变化",
            viral_hook="别急着换，先看这两条事实",
            why_it_may_work="工具选择常被宣传语淹没；固定用两条已核验事实和受众边界，可以避免变成种草或站队。",
            best_scenes=("两个工具出现明确产品差异", "新功能很热但不确定要不要付费", "旧工作流已经够用"),
            content_angle="只解释一个确定变化：至少两条已核验事实、谁应关注、谁能继续观望。",
            saveable_tool="主题 / 两条已核验事实 / 谁该关注 / 谁可以等等",
            comment_prompt="你的任务是否落在“该关注”的受众边界里？",
            avoid="不要做夸张带货、主观性能对比、购买承诺或无证据推荐。",
            format_recommendation=FormatRecommendation(
                format_archetype="note_card",
                cover_role="cover_hook",
                body_shape="one product change / 2 verified facts / should-care and wait boundary",
                visual_evidence_need="low",
                avoid_format=("dense_text_poster", "ranking-poster"),
            ),
            lane_affinity=("工具选择",),
            scene_keywords=("工具", "对比", "选择", "避坑", "适合", "不适合", "付费"),
            base_priority=7,
        ),
        TopicDirection(
            id="ai_ordinary_person_impact",
            name="这项 AI 更新，和哪些任务有关",
            content_mode="fact_translation",
            trend_signal="普通人影响 / 已核验更新",
            viral_hook="不是所有热点，都要立刻跟",
            why_it_may_work="把影响范围拆成明确受众与等待边界，能避开宏大预测，也更贴近读者的具体任务。",
            best_scenes=("AI 新功能进入手机或办公软件", "学习工具出现明确更新", "内容生产工具改变一个具体入口"),
            content_angle="只根据已核验事实说明影响范围：谁会遇到，谁暂时不会遇到。",
            saveable_tool="主题 / 两条事实 / 谁该关注 / 谁可以等等",
            comment_prompt="你的具体任务属于需要关注，还是可以等等？",
            avoid="不要制造失业恐慌、泛泛未来预测、暴富叙事或投资机会。",
            format_recommendation=FormatRecommendation(
                format_archetype="note_card",
                cover_role="cover_hook",
                body_shape="one update / 2 verified facts / audience decision boundary",
                visual_evidence_need="low",
                avoid_format=("dense_text_poster", "future-prediction-poster"),
            ),
            lane_affinity=("普通人影响",),
            scene_keywords=("普通人", "影响", "学习", "内容生产", "边界", "担心", "趋势"),
            base_priority=7,
        ),
        TopicDirection(
            id="ai_agent_handoff_checklist",
            name="Agent 更新怎么读：交接边界写清楚",
            content_mode="fact_translation",
            trend_signal="Agent / 自动执行能力变化",
            viral_hook="能交给 Agent 的范围，先看事实",
            why_it_may_work="Agent 话题很容易被写成全自动想象；用产品的已核验能力与受众边界解释，才不会把风险判断说满。",
            best_scenes=("Agent 出现明确自动执行能力更新", "工具新增任务交接入口", "需要解释人工确认边界"),
            content_angle="围绕一个 Agent 更新，保留两条已核验事实，并写明谁应关注、谁可继续观望。",
            saveable_tool="主题 / 两条事实 / 谁该关注 / 谁可以等等",
            comment_prompt="你的任务里，是否已有明确的交接与人工确认边界？",
            avoid="不要承诺全自动无风险，不虚构交接清单，不做安全、法律或投资确定性建议。",
            format_recommendation=FormatRecommendation(
                format_archetype="note_card",
                cover_role="cover_hook",
                body_shape="one Agent update / 2 verified facts / audience decision boundary",
                visual_evidence_need="low",
                avoid_format=("dense_text_poster", "automation-guarantee-poster"),
            ),
            lane_affinity=("工作流", "普通人影响"),
            scene_keywords=("agent", "Agent", "自动执行", "代理", "任务", "交接", "放手", "盯住"),
            base_priority=6,
            diversity_key="agent-boundary",
        ),
        TopicDirection(
            id="ai_privacy_permission_check",
            name="AI 工具权限更新：哪些团队该看",
            content_mode="fact_translation",
            trend_signal="隐私边界 / 已核验权限变化",
            viral_hook="先别被功能吸引，权限变化先看",
            why_it_may_work="权限议题容易制造恐慌；只讲已核验的权限变化和适用受众，能让判断更克制。",
            best_scenes=("新工具新增明确文件权限", "插件出现已核验连接器变化", "团队准备评估 AI 工具权限"),
            content_angle="围绕一个明确权限或连接器变化，保留两条已核验事实，再给出谁该关注、谁能等待。",
            saveable_tool="主题 / 两条事实 / 谁该关注 / 谁可以等等",
            comment_prompt="你的使用场景是否涉及这次已核验的权限变化？",
            avoid="不要制造隐私恐慌，不替代安全审计或合规意见，不补充未核验的数据处理说法。",
            format_recommendation=FormatRecommendation(
                format_archetype="note_card",
                cover_role="cover_hook",
                body_shape="one permission update / 2 verified facts / audience decision boundary",
                visual_evidence_need="low",
                avoid_format=("dense_text_poster", "security-fear-poster"),
            ),
            lane_affinity=("工具选择", "普通人影响"),
            scene_keywords=("隐私", "权限", "数据", "插件", "邮箱", "日历", "文件", "安全"),
            base_priority=5,
            diversity_key="risk-checklist",
        ),
    ),
)


DAILY_ENGLISH_PACK = TopicPack(
    playbook_id="daily_english_post",
    default_account_id="acct-daily-english-local",
    default_image_style="note_card",
    guidance_message="这条每日英语内容建议先从下面选一个明天能用的表达场景，再进入生成。",
    lanes=(
        TopicLane(
            name="职场表达 / 可复制句型",
            default_scene="学一个表示坚持的高级词汇，想配真实职场例句",
            default_content_angle="用真实工作场景带出表达，给读者一个可替换句型。",
            default_saveable_tool="单词 / 职场例句 / 可替换句型",
            default_comment_prompt="你想用这个表达造一个什么职场句？",
            keywords=("职场", "会议", "邮件", "坚持", "表达", "例句", "高级词汇"),
        ),
        TopicLane(
            name="情绪词 / 场景记忆",
            default_scene="想学一个能表达心累但不夸张的英文词",
            default_content_angle="把情绪词放进真实生活语境，避免词典式解释。",
            default_saveable_tool="情绪词 / 使用场景 / 别这样误用",
            default_comment_prompt="你今天最想表达哪一种情绪？",
            keywords=("情绪", "心累", "焦虑", "开心", "沮丧", "压力", "表达"),
        ),
        TopicLane(
            name="每日一词 / 学习陪伴",
            default_scene="今天只学一个明天聊天就能用的高频词",
            default_content_angle="保持轻量陪伴感，让读者学完能马上用一句。",
            default_saveable_tool="音标 / 词性 / 例句 / 替换模板",
            default_comment_prompt="你用今天这个词造一句，我帮你顺一下。",
            keywords=("每日", "单词", "短语", "高频", "明天", "聊天", "学习"),
        ),
        TopicLane(
            name="评论区造句 / 互动练习",
            default_scene="想做一条评论区可以一起造句的英语表达",
            default_content_angle="把练习设计成低压力互动，不像课堂作业。",
            default_saveable_tool="表达 / 你的例句 / 可以替换的部分",
            default_comment_prompt="把你的句子留在评论区，我帮你改得更自然。",
            keywords=("评论区", "造句", "练习", "改句子", "互动", "自然", "替换"),
        ),
    ),
    directions=(
        TopicDirection(
            id="english_workplace_phrase",
            name="职场表达：一个明天能用的句型",
            trend_signal="职场英语 / 可复制句型",
            viral_hook="收藏模板",
            why_it_may_work="职场表达有明确使用场景，读者能直接把句型替换到会议、邮件或汇报里。",
            best_scenes=("会议里表达坚持", "邮件里委婉推进", "汇报里说明进展"),
            content_angle="不是背一个高级词，而是学一句你明天真的能说出口的话。",
            saveable_tool="单词 / 职场例句 / 可替换句型",
            comment_prompt="你想用这个表达造一个什么职场句？",
            avoid="不要写成词典释义，不要用不自然的中式英文例句。",
            lane_affinity=("职场表达",),
            scene_keywords=("职场", "会议", "邮件", "坚持", "表达", "例句", "高级词汇"),
            base_priority=8,
        ),
        TopicDirection(
            id="english_emotion_word",
            name="情绪词：把心情说得更准确一点",
            trend_signal="情绪表达 / 生活英语",
            viral_hook="评论区交情绪",
            why_it_may_work="情绪词容易有代入感，真实场景例句能让读者感觉学了就能用。",
            best_scenes=("想说心累但不想太dramatic", "表达压力", "聊天里说今天有点撑不住"),
            content_angle="会说情绪，不是为了显得高级，是为了把自己的状态说清楚一点。",
            saveable_tool="情绪词 / 使用场景 / 别这样误用",
            comment_prompt="你今天最想表达哪一种情绪？",
            avoid="不要把情绪表达写成心理诊断，不要堆同义词。",
            lane_affinity=("情绪词",),
            scene_keywords=("情绪", "心累", "焦虑", "开心", "沮丧", "压力", "状态"),
            base_priority=7,
        ),
        TopicDirection(
            id="english_one_word_today",
            name="每日一词：轻量学习搭子",
            trend_signal="每日学习 / 陪伴感",
            viral_hook="打卡但不鸡血",
            why_it_may_work="固定栏目降低阅读压力，轻量例句比完整课程更适合小红书日更。",
            best_scenes=("今天只学一个高频词", "想保持英语手感", "想把热词落成自然英文"),
            content_angle="今天不贪多，只把一个表达学到明天能用。",
            saveable_tool="音标 / 词性 / 例句 / 替换模板",
            comment_prompt="你用今天这个词造一句，我帮你顺一下。",
            avoid="不要写成课堂打卡模板，不要用生僻词制造学习负担。",
            lane_affinity=("每日一词",),
            scene_keywords=("每日", "单词", "短语", "高频", "明天", "聊天", "学习"),
            base_priority=6,
        ),
        TopicDirection(
            id="english_comment_sentence",
            name="评论区造句：把练习变轻一点",
            trend_signal="互动练习 / 评论区共创",
            viral_hook="评论区改句子",
            why_it_may_work="低压力造句能把收藏转成评论互动，也能让读者感觉账号真的在陪练。",
            best_scenes=("学完短语后造句", "读者想知道这样说自然不自然", "把一个中文场景换成英文"),
            content_angle="练英语可以不用像交作业，先留一句，我们一起改得自然一点。",
            saveable_tool="表达 / 你的例句 / 可以替换的部分",
            comment_prompt="把你的句子留在评论区，我帮你改得更自然。",
            avoid="不要用老师批改口吻，不要让读者觉得被考试。",
            lane_affinity=("评论区造句",),
            scene_keywords=(
                "评论区",
                "造句",
                "练习",
                "改句子",
                "互动",
                "自然",
                "替换",
                "英文回复",
                "句子",
            ),
            base_priority=6,
        ),
        TopicDirection(
            id="english_polite_boundary_reply",
            name="委婉拒绝：不生硬的英文边界句",
            trend_signal="职场英语 / 边界表达",
            viral_hook="可复制回复",
            why_it_may_work="拒绝临时会议、改时间、说明限制都很高频，句型能直接被保存和改写。",
            best_scenes=("临时会议不方便参加", "想延期回复", "需要礼貌拒绝额外任务"),
            content_angle="英文里的委婉不是绕圈子，而是把限制说清楚又保留合作感。",
            saveable_tool="中文场景 / 英文回复 / 可替换部分",
            comment_prompt="你最想学哪一句委婉拒绝？",
            avoid="不要写成中式硬翻，不要让句子过度客套到不自然。",
            lane_affinity=("职场表达", "评论区造句"),
            scene_keywords=("拒绝", "委婉", "会议", "回复", "临时", "改时间", "不方便"),
            base_priority=6,
            diversity_key="reply-template",
        ),
        TopicDirection(
            id="english_small_talk_bridge",
            name="破冰小句：把尴尬聊天接住",
            trend_signal="生活英语 / 真实聊天",
            viral_hook="评论区造句",
            why_it_may_work="small talk 是常见痛点，真实场景比抽象词汇更容易让读者开口练。",
            best_scenes=("第一次见同事不知道怎么开口", "线上会议前想自然寒暄", "想把冷场接一下"),
            content_angle="small talk 不必高级，关键是让下一句话变容易。",
            saveable_tool="场景 / 开场句 / 下一句接法",
            comment_prompt="把你的尴尬场景丢来，我帮你改成一句自然英文。",
            avoid="不要堆复杂表达，不把练习写成考试题。",
            lane_affinity=("每日一词", "评论区造句"),
            scene_keywords=("破冰", "寒暄", "聊天", "尴尬", "small talk", "开场", "会议前"),
            base_priority=5,
            diversity_key="conversation-bridge",
        ),
    ),
)


WORLD_CUP_PACK = TopicPack(
    playbook_id="world_cup_daily_post",
    default_account_id="acct-world-cup-local",
    default_image_style="note_card",
    guidance_message="这条世界杯内容建议先从下面选一个普通球迷能参与的看球入口，再进入生成。",
    lanes=(
        TopicLane(
            name="看球清单 / 可保存",
            default_scene="阿根廷和法国决赛前，想写普通球迷看球清单",
            default_content_angle="把比赛写成普通球迷能边看边用的观察清单。",
            default_saveable_tool="比赛语境 / 2-3 个看点 / 看球清单",
            default_comment_prompt="你今晚最想看哪一个对位？",
            keywords=("看球", "清单", "决赛", "赛前", "阿根廷", "法国", "普通球迷"),
        ),
        TopicLane(
            name="球迷情绪 / 看球搭子",
            default_scene="想写一条熬夜看球前的球迷情绪笔记",
            default_content_angle="先写普通球迷的期待、紧张和氛围，再给可聊的看点。",
            default_saveable_tool="情绪入口 / 看点 / 评论区站队",
            default_comment_prompt="你看球时最容易在哪一秒屏住呼吸？",
            keywords=("球迷", "熬夜", "紧张", "期待", "氛围", "搭子", "站队"),
        ),
        TopicLane(
            name="赛前看点 / 人话拆解",
            default_scene="想写一场比赛赛前 3 个普通人能看懂的看点",
            default_content_angle="不装专家，只把战术讲到普通球迷能一起看的层级。",
            default_saveable_tool="看点 / 怎么看 / 聊天话题",
            default_comment_prompt="你最想看哪组对位？",
            keywords=("赛前", "看点", "对位", "边路", "中场", "定位球", "逼抢"),
        ),
        TopicLane(
            name="赛后复盘 / 不预测",
            default_scene="赛后想写一条不装专家的普通球迷复盘",
            default_content_angle="按情绪、关键瞬间和可复盘看点收束，不做确定性预测。",
            default_saveable_tool="关键瞬间 / 普通球迷看法 / 下次看什么",
            default_comment_prompt="这场球你最想复盘哪一个瞬间？",
            keywords=("赛后", "复盘", "关键瞬间", "遗憾", "点球", "加时", "下半场"),
        ),
    ),
    directions=(
        TopicDirection(
            id="worldcup_match_watching_checklist",
            name="看球清单：普通球迷也能一起看",
            trend_signal="看球搭子 / 可保存清单",
            viral_hook="收藏看球卡",
            why_it_may_work="清单形式降低专业门槛，适合赛前收藏、赛中对照和评论区一起补充。",
            best_scenes=("决赛赛前", "淘汰赛焦点战", "朋友一起看球前"),
            content_angle="今晚不用装懂球，先带着这 3 个问题看就够了。",
            saveable_tool="比赛语境 / 2-3 个看点 / 看球清单",
            comment_prompt="你今晚最想看哪一个对位？",
            avoid="不要写赌球、盘口、下注建议、确定性比分预测或内部消息。",
            lane_affinity=("看球清单",),
            scene_keywords=("看球", "清单", "决赛", "赛前", "阿根廷", "法国", "普通球迷"),
            base_priority=8,
        ),
        TopicDirection(
            id="worldcup_fan_emotion_note",
            name="球迷情绪：熬夜前那一点紧张",
            trend_signal="球迷情绪 / 氛围感",
            viral_hook="评论区站队",
            why_it_may_work="情绪入口比专业赛报更有参与感，能让轻度球迷也愿意评论。",
            best_scenes=("熬夜看球", "朋友约球局", "点球前屏住呼吸"),
            content_angle="世界杯最动人的不只是比分，还有一群人同时紧张的那几分钟。",
            saveable_tool="情绪入口 / 看点 / 评论区站队",
            comment_prompt="你看球时最容易在哪一秒屏住呼吸？",
            avoid="不要拉踩球队或球迷，不要制造饭圈对立。",
            lane_affinity=("球迷情绪",),
            scene_keywords=("球迷", "熬夜", "紧张", "期待", "氛围", "搭子", "站队"),
            base_priority=7,
        ),
        TopicDirection(
            id="worldcup_plain_preview",
            name="赛前看点：把战术讲成人话",
            trend_signal="赛前看点 / 人话拆解",
            viral_hook="2-3 个看点",
            why_it_may_work="赛前内容有强搜索入口，人话拆解能避免普通读者被专业术语挡住。",
            best_scenes=("赛前 2 小时", "强强对话", "普通球迷想知道看什么"),
            content_angle="这场不用背术语，先看中场节奏、边路空间和定位球这几件事。",
            saveable_tool="看点 / 怎么看 / 聊天话题",
            comment_prompt="你最想看哪组对位？",
            avoid="不要把未确认的首发、伤病或赛程写成事实。",
            lane_affinity=("赛前看点",),
            scene_keywords=("赛前", "看点", "对位", "边路", "中场", "定位球", "逼抢"),
            base_priority=7,
        ),
        TopicDirection(
            id="worldcup_post_match_reframe",
            name="赛后复盘：先收住情绪，再看三个瞬间",
            trend_signal="赛后复盘 / 普通球迷视角",
            viral_hook="复盘顺序",
            why_it_may_work="赛后情绪强，给一个复盘顺序能把争吵转成可讨论的关键瞬间。",
            best_scenes=("赛后很遗憾", "点球大战结束", "想讨论但不想吵架"),
            content_angle="赛后不是马上找战犯，先把真正改变比赛的几个瞬间看清楚。",
            saveable_tool="关键瞬间 / 普通球迷看法 / 下次看什么",
            comment_prompt="这场球你最想复盘哪一个瞬间？",
            avoid="不要写确定性预测，不要冒充官方消息或内部消息。",
            lane_affinity=("赛后复盘",),
            scene_keywords=("赛后", "复盘", "关键瞬间", "遗憾", "点球", "加时", "下半场"),
            base_priority=6,
        ),
        TopicDirection(
            id="worldcup_watch_party_setup",
            name="看球局准备：普通球迷的熬夜小清单",
            trend_signal="看球搭子 / 氛围感",
            viral_hook="低门槛准备清单",
            why_it_may_work="看球局、熬夜和朋友氛围比战术更有生活代入，适合轻度球迷参与。",
            best_scenes=("朋友约看球局", "熬夜看焦点战", "想准备零食和聊天话题"),
            content_angle="看球局不是要装懂，先把一起紧张的氛围准备好。",
            saveable_tool="时间 / 准备物 / 可以聊的 3 个看点",
            comment_prompt="你看球局一定会准备什么？",
            avoid="不要引导饮酒过量，不写赌球、下注或盘口。",
            lane_affinity=("球迷情绪", "看球清单"),
            scene_keywords=("看球局", "朋友", "熬夜", "准备", "氛围", "零食", "投屏", "一起看"),
            base_priority=6,
            diversity_key="watch-party",
        ),
        TopicDirection(
            id="worldcup_player_story_entry",
            name="球员故事入口：先认识一个人，再看一场球",
            trend_signal="球员故事 / 普通人入口",
            viral_hook="人物小卡",
            why_it_may_work="人物故事能降低赛事门槛，让不熟悉战术的读者也有进入比赛的理由。",
            best_scenes=("想介绍一位核心球员", "朋友问这场看谁", "赛前需要一个人物入口"),
            content_angle="有时候先认识一个人，比赛就从比分变成了故事。",
            saveable_tool="球员 / 一个背景 / 这场重点看什么",
            comment_prompt="你是因为哪位球员开始看世界杯的？",
            avoid="不要编造经历、伤病或官方消息，不做确定性表现预测。",
            lane_affinity=("赛前看点",),
            scene_keywords=("球员", "人物", "故事", "核心", "看谁", "背景", "认识"),
            base_priority=5,
            diversity_key="player-story",
        ),
        TopicDirection(
            id="worldcup_friend_chat_prompt",
            name="朋友看球局：先准备三句能聊的话",
            trend_signal="看球搭子 / 评论区话题",
            viral_hook="聊天话题卡",
            why_it_may_work="很多轻度球迷需要的不是战术课，而是看球时能自然参与的三句话。",
            best_scenes=("朋友约了看球局", "不太懂球但想参与聊天", "熬夜前准备几个话题"),
            content_angle="看球局里最有用的准备，有时是三句能接住气氛的话。",
            saveable_tool="我看谁 / 我问什么 / 我可以怎么接话",
            comment_prompt="你看球局最常说哪一句？",
            avoid="不要制造球队对立，不写赌球、盘口或比分预测。",
            lane_affinity=("球迷情绪",),
            scene_keywords=("朋友", "看球局", "聊天", "话题", "熬夜", "准备", "不懂球"),
            base_priority=5,
            diversity_key="chat-prompt",
        ),
    ),
)


REDDIT_CURATION_PACK = TopicPack(
    playbook_id="reddit_curation_daily_post",
    default_account_id="acct-reddit-curation-local",
    default_image_style="note_card",
    guidance_message="这条外网讨论转译内容建议先从下面选一个适合中文读者的热点观察角度，再进入生成。",
    lanes=(
        TopicLane(
            name="AI 工具焦虑 / 中文语境",
            default_scene="从外网 AI 工具焦虑讨论里选一个适合中文读者的角度",
            default_content_angle="把英文社区现象消化成中文读者能共鸣的 AI 使用压力。",
            default_saveable_tool="现象 / 核心判断 / 可收藏小结",
            default_comment_prompt="你现在更像是在用 AI，还是在照看 AI？",
            keywords=("外网", "AI", "工具", "焦虑", "中文读者", "讨论", "压力"),
        ),
        TopicLane(
            name="效率工作流 / 经验转译",
            default_scene="想把海外用户的效率工具经验写成中文读者可用的小结",
            default_content_angle="不搬运个案，只提炼一个中文读者能试的工作流判断。",
            default_saveable_tool="场景 / 做法 / 适合先试的人",
            default_comment_prompt="你最想优化哪一步工作流？",
            keywords=("效率", "工作流", "经验", "工具", "productivity", "方法", "小结"),
        ),
        TopicLane(
            name="生活压力 / 非诊断观察",
            default_scene="想写一种大家都在被消息和工具追着跑的生活压力",
            default_content_angle="把生活压力写成普通人的观察，不诊断、不承诺治愈。",
            default_saveable_tool="压力来源 / 共鸣点 / 今天能停在哪一步",
            default_comment_prompt="你最近最想先停下哪一个信息入口？",
            keywords=("生活", "压力", "消息", "注意力", "心理", "情绪", "停不下来"),
        ),
        TopicLane(
            name="中文读者角度 / 为什么值得关心",
            default_scene="想写一个外网热点为什么会让中文读者也有感觉",
            default_content_angle="先解释这个现象为什么值得中文读者关心，再给一条可讨论判断。",
            default_saveable_tool="现象 / 为什么有关 / 你可以怎么判断",
            default_comment_prompt="这个现象让你想到自己哪一个场景？",
            keywords=("中文读者", "热点", "现象", "为什么", "共鸣", "观察", "判断"),
        ),
    ),
    directions=(
        TopicDirection(
            id="reddit_ai_tool_anxiety",
            name="AI 工具焦虑：到底是谁在被谁训练",
            trend_signal="AI 工具焦虑 / 普通人压力",
            viral_hook="一句判断引评论",
            why_it_may_work="AI 工具焦虑是跨平台共鸣点，中文读者也容易代入被工具节奏追着跑的感受。",
            best_scenes=("工具越装越多", "为了效率反而更累", "不知道该不该跟新模型"),
            content_angle="很多人不是不会用 AI，而是开始觉得自己每天都在照看一堆工具。",
            saveable_tool="现象 / 核心判断 / 可收藏小结",
            comment_prompt="你现在更像是在用 AI，还是在照看 AI？",
            avoid="不要展示平台名、用户身份、链接或翻译过程，不要做投资建议。",
            lane_affinity=("AI 工具焦虑",),
            scene_keywords=("外网", "AI", "工具", "焦虑", "中文读者", "讨论", "压力"),
            base_priority=8,
        ),
        TopicDirection(
            id="reddit_workflow_case",
            name="效率工作流：一个能先试的小改法",
            trend_signal="效率工具 / 工作流经验",
            viral_hook="可保存小结",
            why_it_may_work="把经验转成可试步骤，比搬运讨论更适合小红书收藏。",
            best_scenes=("整理资料太散", "AI 工具接不上旧流程", "想用一个小改法省重复劳动"),
            content_angle="真正有用的工作流，不是工具越多越好，而是少一个反复切换的动作。",
            saveable_tool="场景 / 做法 / 适合先试的人",
            comment_prompt="你最想优化哪一步工作流？",
            avoid="不要把别人的经历写成作者亲历，不要复制长段英文原文。",
            lane_affinity=("效率工作流",),
            scene_keywords=("效率", "工作流", "经验", "工具", "productivity", "方法", "小结"),
            base_priority=7,
        ),
        TopicDirection(
            id="reddit_psych_life_pressure",
            name="生活压力观察：消息和工具都在追人",
            trend_signal="注意力压力 / 非诊断观察",
            viral_hook="评论区共鸣",
            why_it_may_work="消息压力和工具压力是普遍体验，非诊断化表达能兼顾共鸣与安全边界。",
            best_scenes=("消息回不完", "工具提醒太多", "想提高效率却越来越碎"),
            content_angle="有时让人累的不是某一个任务，而是每个入口都在说快一点。",
            saveable_tool="压力来源 / 共鸣点 / 今天能停在哪一步",
            comment_prompt="你最近最想先停下哪一个信息入口？",
            avoid="不要做心理诊断，不要承诺治愈，不要建议用药。",
            lane_affinity=("生活压力",),
            scene_keywords=("生活", "压力", "消息", "注意力", "心理", "情绪", "停不下来"),
            base_priority=6,
        ),
        TopicDirection(
            id="reddit_chinese_reader_angle",
            name="中文读者为什么也会关心这个热点",
            trend_signal="热点观察 / 中文语境",
            viral_hook="关系到我吗",
            why_it_may_work="先回答为什么有关，能把外部讨论转成中文读者愿意停下来的判断。",
            best_scenes=("外部热点很热但离读者有距离", "AI 或效率议题需要本地化理解", "想写成中文语境观察"),
            content_angle="一个热点值不值得看，关键不是它有多热，而是它改变了普通人的哪个默认动作。",
            saveable_tool="现象 / 为什么有关 / 你可以怎么判断",
            comment_prompt="这个现象让你想到自己哪一个场景？",
            avoid="不要展示采集过程、原始讨论位置、链接或账号身份。",
            lane_affinity=("中文读者角度",),
            scene_keywords=("中文读者", "热点", "现象", "为什么", "共鸣", "观察", "判断"),
            base_priority=6,
        ),
        TopicDirection(
            id="reddit_comment_conflict_pattern",
            name="评论区两派：为什么大家吵的是同一个焦虑",
            trend_signal="外网争论 / 中文语境",
            viral_hook="两派观点卡",
            why_it_may_work="把争论翻译成两个可理解的普通人立场，读者更容易参与而不是围观搬运。",
            best_scenes=("外网评论区吵成两派", "同一个工具有人夸有人骂", "热点争论需要中文化解释"),
            content_angle="很多看起来互相反驳的评论，其实都在担心同一件事。",
            saveable_tool="A 派担心 / B 派担心 / 中文读者先看什么",
            comment_prompt="这件事你更站哪一派，还是两边都懂？",
            avoid="不要展示原始平台、账号、链接或长段英文原文，不煽动对立。",
            lane_affinity=("中文读者角度",),
            scene_keywords=("评论区", "两派", "吵", "争论", "观点", "站哪边", "外网"),
            base_priority=6,
            diversity_key="conflict-map",
        ),
        TopicDirection(
            id="reddit_ai_stop_rule",
            name="AI 使用停机规则：别让工具把一天切碎",
            trend_signal="AI 工具焦虑 / 注意力边界",
            viral_hook="可保存停止规则",
            why_it_may_work="AI 工具焦虑和生活压力可以合并成一个可执行的停止规则，避免只做情绪共鸣。",
            best_scenes=("工具越开越多", "为了效率反而更碎", "反复切换 AI、文档和消息"),
            content_angle="真正拖累人的不一定是工具本身，而是每个工具都在要求你立刻切过去。",
            saveable_tool="现在开了什么 / 哪个先关掉 / 下一步只做什么",
            comment_prompt="你最想先关掉哪一个效率入口？",
            avoid="不要做心理诊断，不声称来自具体外网个案。",
            lane_affinity=("AI 工具焦虑", "生活压力"),
            scene_keywords=("AI", "工具", "切换", "停机", "效率", "消息", "注意力", "切碎"),
            base_priority=5,
            diversity_key="stop-rule",
        ),
    ),
)


TOPIC_GUIDANCE_PACKS = {
    FENGKUANG_PACK.playbook_id: FENGKUANG_PACK,
    HUMAN_ENRICHMENT_PACK.playbook_id: HUMAN_ENRICHMENT_PACK,
    CLASSIC_POETRY_PACK.playbook_id: CLASSIC_POETRY_PACK,
    WUXIA_CHARACTER_PACK.playbook_id: WUXIA_CHARACTER_PACK,
    AI_TECH_PACK.playbook_id: AI_TECH_PACK,
    DAILY_ENGLISH_PACK.playbook_id: DAILY_ENGLISH_PACK,
    WORLD_CUP_PACK.playbook_id: WORLD_CUP_PACK,
    REDDIT_CURATION_PACK.playbook_id: REDDIT_CURATION_PACK,
}

DEFAULT_ACCOUNT_BY_PLAYBOOK = {
    playbook_id: pack.default_account_id
    for playbook_id, pack in TOPIC_GUIDANCE_PACKS.items()
}
