from __future__ import annotations

from ptsm.domain.topic_guidance import TopicDirection, TopicLane, TopicPack


FENGKUANG_PACK = TopicPack(
    playbook_id="fengkuang_daily_post",
    default_account_id="acct-fk-local",
    default_image_style="note_card",
    guidance_message="这条发疯文学内容建议先从下面选一个可接龙方向，再进入生成。",
    lanes=(
        TopicLane(
            name="职场物件 / 替人发疯",
            default_scene="领导18:57发来一句在吗，工牌想替我发疯",
            default_content_angle="让一个具体物件替打工人说出没发出去的疯话。",
            default_saveable_tool="物件 / 疯话 / 体面翻译三栏",
            default_comment_prompt="你今天想让哪个物件替你发疯？",
            keywords=("工牌", "电脑", "键盘", "杯子", "领导", "工位", "物件"),
        ),
        TopicLane(
            name="高雅外壳 / 狼狈内核",
            default_scene="明明只是被临时加活，却想写成一碗丝瓜汤",
            default_content_angle="用体面词包装狼狈现场，让反差成为笑点。",
            default_saveable_tool="原句 / 高雅说法 / 实际意思",
            default_comment_prompt="你还有什么高雅外壳的狼狈句？",
            keywords=("高雅", "狼狈", "丝瓜汤", "体面", "翻译"),
        ),
        TopicLane(
            name="群聊未发送 / 评论区接龙",
            default_scene="群聊里那句没发出去的话，最后让评论区替我说了",
            default_content_angle="把没发出去的一句话变成评论区接龙入口。",
            default_saveable_tool="场景 / 没发出去的话 / 体面版本",
            default_comment_prompt="把你没发出去的那句话留在评论区。",
            keywords=("群聊", "没发", "回复", "接龙", "消息", "在吗"),
        ),
        TopicLane(
            name="体面人设 / 活人崩溃",
            default_scene="表面收到，实际灵魂已经从会议室离职",
            default_content_angle="表面维持体面，内核保留活人的荒诞反应。",
            default_saveable_tool="表面台词 / 内心字幕 / 今日缓冲词",
            default_comment_prompt="你今天哪一秒最像体面外壳裂开？",
            keywords=("体面", "收到", "会议", "崩溃", "活人", "下班"),
        ),
    ),
    directions=(
        TopicDirection(
            id="fk_work_object_vent",
            name="职场物件替人发疯",
            trend_signal="物件发疯 / 抽象力",
            viral_hook="评论区补一句",
            why_it_may_work="把情绪交给工牌、键盘、杯子这类具体物件，既有代入感，也方便评论区接力。",
            best_scenes=("领导临下班发在吗", "工牌像替身一样挂了一天", "电脑风扇比人先崩溃"),
            content_angle="不是人在发疯，是工牌终于替我把那句话说出来了。",
            saveable_tool="物件 / 它想说的话 / 体面翻译",
            comment_prompt="你今天想让哪个物件替你发疯？",
            avoid="不要拿心理疾病、医院、治疗或用药当笑点。",
            lane_affinity=("职场物件",),
            scene_keywords=("工牌", "键盘", "电脑", "杯子", "领导", "工位", "发疯"),
            base_priority=8,
        ),
        TopicDirection(
            id="fk_loofah_soup_reply",
            name="丝瓜汤式复盘",
            trend_signal="丝瓜汤 / 高雅外壳",
            viral_hook="可复制疯话",
            why_it_may_work="用高雅句式包住真实狼狈，反差强，也能让用户贡献自己的体面翻译。",
            best_scenes=("被安排临时需求", "一句收到背后有很多话", "想把崩溃写得很讲究"),
            content_angle="把不想干写成一碗温润的丝瓜汤，体面但不失真。",
            saveable_tool="原句 / 丝瓜汤说法 / 实际意思",
            comment_prompt="你还有哪句适合熬成丝瓜汤？",
            avoid="不要攻击具体个人，不要变成阴阳怪气人身攻击。",
            lane_affinity=("高雅外壳",),
            scene_keywords=("丝瓜汤", "高雅", "体面", "临时", "收到", "复盘"),
            base_priority=7,
        ),
        TopicDirection(
            id="fk_group_chat_unsent_line",
            name="群聊没发出去的话",
            trend_signal="打工人关系角色",
            viral_hook="接龙",
            why_it_may_work="未发送消息是高频场景，评论区天然会接自己的那一句。",
            best_scenes=("群聊里忍住没回", "领导发在吗", "同事让你帮忙兜底"),
            content_angle="最疯的不是发出去的话，是删掉以后还在脑子里加班的那句。",
            saveable_tool="场景 / 没发出去的话 / 体面版本",
            comment_prompt="把你没发出去的那句话交出来。",
            avoid="不要鼓励网暴、挂人或泄露真实聊天隐私。",
            lane_affinity=("群聊未发送",),
            scene_keywords=("群聊", "没发", "没发出去", "在吗", "消息", "回复", "领导"),
            base_priority=7,
        ),
        TopicDirection(
            id="fk_polite_shell_wild_core",
            name="体面外壳狼狈内核",
            trend_signal="高雅外壳 / 活人感",
            viral_hook="身份认领",
            why_it_may_work="体面与狼狈的反差容易被认领，也能保持发疯文学的分寸。",
            best_scenes=("表面说收到", "会后还在脑内骂骂咧咧", "下班路上突然想通又没想通"),
            content_angle="体面是外壳，活人才是内核。",
            saveable_tool="表面台词 / 内心字幕 / 今日缓冲词",
            comment_prompt="你今天是哪一种体面外壳？",
            avoid="不要把崩溃写成伤害自己或他人的行动建议。",
            lane_affinity=("体面人设", "高雅外壳"),
            scene_keywords=("体面", "收到", "狼狈", "活人", "崩溃", "下班"),
            base_priority=6,
        ),
    ),
)


HUMAN_ENRICHMENT_PACK = TopicPack(
    playbook_id="human_enrichment_daily_post",
    default_account_id="acct-enrichment-local",
    default_image_style="note_card",
    guidance_message="这条人类丰容内容建议先从下面选一个低成本变量方向，再进入生成。",
    lanes=(
        TopicLane(
            name="一平米角落 / 低成本变量",
            default_scene="把书桌角落改成十分钟适我主义手作位",
            default_content_angle="不是改造整个家，只给一个角落加一个下班信号。",
            default_saveable_tool="原本惯性 / 一个变量 / 今天能试的一步",
            default_comment_prompt="你先想丰容哪个角落？",
            keywords=("书桌", "角落", "工位", "床头", "玄关", "适我主义"),
        ),
        TopicLane(
            name="睡前下线 / 微仪式",
            default_scene="床头只放充电线，睡前总觉得没下线",
            default_content_angle="给睡前十分钟加一个可重复的结束信号。",
            default_saveable_tool="入口 / 下线动作 / 明天第一步",
            default_comment_prompt="你想先给哪个入口下线？",
            keywords=("床头", "睡前", "下线", "十分钟", "充电线"),
        ),
        TopicLane(
            name="通勤路线 / Colorwalk",
            default_scene="下班路上给自己一个找绿色的任务",
            default_content_angle="不换城市，只给通勤路线加一个感官变量。",
            default_saveable_tool="路线 / 颜色任务 / 拍到的一处细节",
            default_comment_prompt="你会给通勤加什么颜色任务？",
            keywords=("通勤", "路线", "colorwalk", "颜色", "下班路"),
        ),
        TopicLane(
            name="手作材料 / 心流平铺",
            default_scene="把手作材料摊开，先做十分钟就停",
            default_content_angle="材料平铺比成品更容易展示今天能开始的一步。",
            default_saveable_tool="材料 / 十分钟动作 / 停止点",
            default_comment_prompt="你最想摊开哪一种材料？",
            keywords=("手作", "材料", "心流", "平铺", "十分钟"),
        ),
    ),
    directions=(
        TopicDirection(
            id="enrichment_desk_corner_variable",
            name="一平米角落：书桌下班信号",
            trend_signal="适我主义 / 新独居",
            viral_hook="低成本 before/after",
            why_it_may_work="具体角落加三步清单容易收藏，也容易让评论区交作业。",
            best_scenes=("书桌太像工位", "床头只有充电线", "玄关一进门就很乱"),
            content_angle="不是改造整个家，只是给一个角落加一个下班信号。",
            saveable_tool="原本惯性 / 一个变量 / 今天能试的一步",
            comment_prompt="你先想丰容哪个角落？",
            avoid="不要写成购物清单，不要用 AI 图伪装真实改造。",
            lane_affinity=("一平米角落",),
            scene_keywords=("书桌", "角落", "工位", "适我主义", "低成本"),
            base_priority=8,
        ),
        TopicDirection(
            id="enrichment_bedside_shutdown_signal",
            name="床头下线信号",
            trend_signal="睡前十分钟",
            viral_hook="三步清单",
            why_it_may_work="睡前场景高频，三步下线动作比宏大自律更容易被保存。",
            best_scenes=("床头只有充电线", "睡前刷手机停不下来", "想让房间有结束感"),
            content_angle="丰容不是多买东西，是让身体知道今天可以结束了。",
            saveable_tool="关入口 / 留明天第一步 / 放一个低刺激物件",
            comment_prompt="你想给睡前加哪一个下线信号？",
            avoid="不要做助眠治疗承诺，不要把失眠简单归因于自控力。",
            lane_affinity=("睡前下线",),
            scene_keywords=("床头", "睡前", "下线", "充电线", "十分钟"),
            base_priority=7,
        ),
        TopicDirection(
            id="enrichment_route_colorwalk",
            name="通勤路线微变量",
            trend_signal="Colorwalk / 低成本行动",
            viral_hook="交作业",
            why_it_may_work="路线变量不需要购物，评论区可以用颜色任务交作业。",
            best_scenes=("每天同一条下班路", "周末不想远行", "想低成本找回一点新鲜感"),
            content_angle="不换城市，也能把今天的路线换一个观察方式。",
            saveable_tool="路线 / 颜色 / 一张细节照片",
            comment_prompt="你明天的通勤颜色任务是什么？",
            avoid="不要写成旅游攻略，也不要暗示危险拍摄或影响通行。",
            lane_affinity=("通勤路线",),
            scene_keywords=("通勤", "路线", "colorwalk", "颜色", "下班路"),
            base_priority=6,
        ),
        TopicDirection(
            id="enrichment_handmade_material_flow",
            name="手作材料平铺",
            trend_signal="手作心流",
            viral_hook="过程轮播",
            why_it_may_work="材料和过程比完美成品更有真实感，也适合轮播拆步骤。",
            best_scenes=("想做手作但迟迟没开始", "材料堆在角落", "只想做十分钟"),
            content_angle="今天不追求完成，只把材料摊开，让开始变小。",
            saveable_tool="材料 / 十分钟动作 / 停止点",
            comment_prompt="你最想摊开哪一种材料？",
            avoid="不要写成昂贵工具种草，不要把失败手作包装成完美教程。",
            lane_affinity=("手作材料",),
            scene_keywords=("手作", "材料", "心流", "平铺", "十分钟"),
            base_priority=6,
        ),
    ),
)


SUSHI_POETRY_PACK = TopicPack(
    playbook_id="sushi_poetry_daily_post",
    default_account_id="acct-sushi-local",
    default_image_style="note_card",
    guidance_message="这条苏轼诗词内容建议先从下面选一个当代生活入口，再进入生成。",
    lanes=(
        TopicLane(
            name="怀民关系 / 角色认领",
            default_scene="夜里读到怀民亦未寝，想写一种旧友关系",
            default_content_angle="从一句词落回当代人想找一个旧友说话的瞬间。",
            default_saveable_tool="词句 / 当代瞬间 / 可保存小纸条",
            default_comment_prompt="你是会叫怀民的人，还是会被叫起来的人？",
            keywords=("怀民", "旧友", "朋友", "夜里", "未寝"),
        ),
        TopicLane(
            name="旧物旧友 / 精神充电",
            default_scene="翻到一件旧物，突然想起一个老朋友",
            default_content_angle="用旧物作为入口，把诗词写成一次温和的精神充电。",
            default_saveable_tool="旧物 / 词句 / 今天能写的一句",
            default_comment_prompt="你会把哪件旧物交给苏轼？",
            keywords=("旧物", "旧友", "老朋友", "精神", "充电"),
        ),
        TopicLane(
            name="节气小动作 / 生活仪式",
            default_scene="一个节气里只做一件小事",
            default_content_angle="把节气从知识点写成今天能做的小动作。",
            default_saveable_tool="节气 / 一件小事 / 一句词",
            default_comment_prompt="这个节气你想做哪件小事？",
            keywords=("节气", "非遗", "季节", "小动作", "仪式"),
        ),
        TopicLane(
            name="坏天气 / 定风波重读",
            default_scene="今天过得很狼狈，想借定风波重新看一眼",
            default_content_angle="不把狼狈美化，只借苏轼给它一个可放下的句子。",
            default_saveable_tool="狼狈场景 / 词句 / 放下一步",
            default_comment_prompt="你今天最想把哪点狼狈写进一句词？",
            keywords=("定风波", "狼狈", "坏天气", "风雨", "放下"),
        ),
    ),
    directions=(
        TopicDirection(
            id="sushi_role_pair_huimin",
            name="苏轼/怀民关系角色",
            trend_signal="文化力 / 角色认领",
            viral_hook="你是 A 还是 B",
            why_it_may_work="怀民是天然评论入口，读者容易认领自己是叫人的人还是被叫起来的人。",
            best_scenes=("夜里想找旧友说话", "朋友一句普通回复让人缓过来", "读到怀民亦未寝"),
            content_angle="不是只有宏大的友情，半夜有人知道你还醒着也很珍贵。",
            saveable_tool="词句 / 当代瞬间 / 可保存小纸条",
            comment_prompt="你是会叫怀民的人，还是会被叫起来的人？",
            avoid="不要写成百科讲义，不要过度神化古人关系。",
            lane_affinity=("怀民关系",),
            scene_keywords=("怀民", "未寝", "旧友", "朋友", "夜里", "关系"),
            base_priority=8,
        ),
        TopicDirection(
            id="sushi_old_friend_note",
            name="旧友旧物里的精神充电",
            trend_signal="旧物 / 活人感",
            viral_hook="评论交一个人",
            why_it_may_work="旧物和旧友能把诗词从知识点变成普通人的记忆入口。",
            best_scenes=("翻到旧照片", "想起一个很久没联系的人", "被一件小物件安慰"),
            content_angle="旧物不是怀旧滤镜，是提醒你曾经被认真陪过。",
            saveable_tool="旧物 / 词句 / 今天能写的一句",
            comment_prompt="你想把哪位旧友交给评论区？",
            avoid="不要暴露他人隐私，不要写成伤感煽情长文。",
            lane_affinity=("旧物旧友",),
            scene_keywords=("旧物", "旧友", "老朋友", "照片", "精神", "充电"),
            base_priority=7,
        ),
        TopicDirection(
            id="sushi_season_micro_ritual",
            name="节气里的小动作",
            trend_signal="节气 / 非遗",
            viral_hook="可保存小纸条",
            why_it_may_work="节气话题有搜索入口，小动作能避免百科腔。",
            best_scenes=("立夏想做一件小事", "下雨天泡一杯茶", "季节变化时想慢一点"),
            content_angle="节气不是知识点，是今天可以慢慢做的一件小事。",
            saveable_tool="节气 / 一件小事 / 一句词",
            comment_prompt="这个节气你想做哪件小事？",
            avoid="不要伪造民俗出处，不要把节气写成空泛鸡汤。",
            lane_affinity=("节气小动作",),
            scene_keywords=("节气", "非遗", "季节", "小动作", "仪式"),
            base_priority=6,
        ),
        TopicDirection(
            id="sushi_bad_day_reframe",
            name="把狼狈写进一句词",
            trend_signal="柔软力",
            viral_hook="轻量重读",
            why_it_may_work="坏天气和狼狈感高代入，苏轼词句能给出轻量重读而不是说教。",
            best_scenes=("今天很狼狈", "遇到坏天气", "读到定风波想放过自己"),
            content_angle="不是把狼狈变美，而是给它一个可以暂时放下的句子。",
            saveable_tool="狼狈场景 / 词句 / 放下一步",
            comment_prompt="你今天最想把哪点狼狈写进一句词？",
            avoid="不要用诗词否定现实困难，也不要写成万能治愈。",
            lane_affinity=("坏天气",),
            scene_keywords=("定风波", "狼狈", "风雨", "坏天气", "放下"),
            base_priority=6,
        ),
    ),
)


WUXIA_CHARACTER_PACK = TopicPack(
    playbook_id="wuxia_character_post",
    default_account_id="acct-wuxia-local",
    default_image_style="note_card",
    guidance_message="这条武侠人物评述建议先从下面选一个当代生活入口，再进入生成。",
    lanes=(
        TopicLane(
            name="老款人格 / 角色认领",
            default_scene="想用令狐冲写一种当代职场里的自由人格",
            default_content_angle="把武侠人物从剧情简介里拉回当代人的性格认领。",
            default_saveable_tool="人物 / 当代处境 / 一句可截图判断",
            default_comment_prompt="你最像哪一种老款人格？",
            keywords=("令狐冲", "郭靖", "黄蓉", "杨过", "小龙女", "老款人格", "自由"),
        ),
        TopicLane(
            name="当代职场 / 江湖镜像",
            default_scene="用黄蓉写一个今天也能看懂的职场判断",
            default_content_angle="把门派、江湖和人情写成今天的组织关系和能力选择。",
            default_saveable_tool="江湖处境 / 职场镜像 / 今日判断",
            default_comment_prompt="你觉得哪个武侠人物最像今天的职场人？",
            keywords=("职场", "领导", "同事", "组织", "能力", "CEO", "黄蓉"),
        ),
        TopicLane(
            name="主体性 / 边界选择",
            default_scene="想写小龙女不是冷淡，而是在守住自己的选择",
            default_content_angle="用人物处境讨论主体性和边界，不把复杂人物压扁成标签。",
            default_saveable_tool="人物选择 / 代价 / 今天能借的一句话",
            default_comment_prompt="你最想替哪个人物说一句公道话？",
            keywords=("主体性", "边界", "选择", "小龙女", "黄蓉", "郭靖", "杨过"),
        ),
        TopicLane(
            name="人情债 / 关系困局",
            default_scene="用李寻欢写一种很会还人情、也很会为难自己的关系",
            default_content_angle="把江湖人情债翻译成当代关系里的亏欠、体面和自我消耗。",
            default_saveable_tool="人情债 / 真实选择 / 评论区问题",
            default_comment_prompt="你最想聊哪一种江湖人情债？",
            keywords=("人情", "亏欠", "关系", "李寻欢", "古龙", "体面", "自我消耗"),
        ),
    ),
    directions=(
        TopicDirection(
            id="wuxia_old_school_personality",
            name="老款人格：今天你像哪位江湖人",
            trend_signal="老款人格 / 角色认领",
            viral_hook="评论区认领",
            why_it_may_work="武侠人物自带记忆点，老款人格能让读者把角色复杂性和自己的当代处境连起来。",
            best_scenes=("令狐冲的自由感", "郭靖的笨拙可靠", "黄蓉的聪明和责任"),
            content_angle="不是把人物贴标签，而是从一个选择里看见今天还在发生的人格困境。",
            saveable_tool="人物 / 当代处境 / 一句可截图判断",
            comment_prompt="你今天最像哪位江湖人？",
            avoid="不要写成百科词条，不要只复述剧情。",
            lane_affinity=("老款人格", "角色认领"),
            scene_keywords=("令狐冲", "郭靖", "黄蓉", "杨过", "小龙女", "老款人格", "自由"),
            base_priority=8,
        ),
        TopicDirection(
            id="wuxia_workplace_mirror",
            name="武侠人物照进当代职场",
            trend_signal="职场镜像 / 文化力",
            viral_hook="当代人代入",
            why_it_may_work="把江湖处境翻译成职场关系，既有观点，也能降低古典内容的进入门槛。",
            best_scenes=("黄蓉像被低估的组织者", "令狐冲不适合被 KPI 驯化", "郭靖的慢就是护城河"),
            content_angle="江湖不是离我们很远，很多门派关系只是换了一个办公室名字。",
            saveable_tool="江湖处境 / 职场镜像 / 今日判断",
            comment_prompt="你觉得谁最像今天的职场人？",
            avoid="不要过度现代化硬套，不要把人物压扁成职场标签。",
            lane_affinity=("当代职场",),
            scene_keywords=("职场", "工位", "领导", "同事", "组织", "黄蓉", "CEO", "KPI"),
            base_priority=7,
        ),
        TopicDirection(
            id="wuxia_boundary_choice",
            name="主体性：人物真正守住的那条边界",
            trend_signal="主体性 / 边界感",
            viral_hook="替人物说句公道话",
            why_it_may_work="边界和主体性是当代高共鸣词，但用人物选择承接，能避免空泛鸡汤。",
            best_scenes=("小龙女的冷淡被误读", "黄蓉的聪明不只是讨好", "杨过的选择需要代价"),
            content_angle="真正动人的不是他做了正确选择，而是他承担了选择的代价。",
            saveable_tool="人物选择 / 代价 / 今天能借的一句话",
            comment_prompt="你最想替哪个人物说一句公道话？",
            avoid="不要把复杂关系写成单一价值评判。",
            lane_affinity=("主体性", "边界"),
            scene_keywords=("主体性", "边界", "选择", "小龙女", "黄蓉", "杨过", "代价"),
            base_priority=7,
        ),
        TopicDirection(
            id="wuxia_relationship_debt",
            name="江湖人情债：体面背后的自我消耗",
            trend_signal="关系压力 / 人情债",
            viral_hook="评论区交一个关系",
            why_it_may_work="人情债能把武侠人物的义气、亏欠和牺牲转成现实关系讨论，评论区容易有故事。",
            best_scenes=("李寻欢的体面让自己受伤", "郭靖背着很多人的期待", "杨过在亏欠里寻找自己"),
            content_angle="很多江湖困局，今天换个名字叫不好意思拒绝。",
            saveable_tool="人情债 / 真实选择 / 评论区问题",
            comment_prompt="你最想聊哪一种江湖人情债？",
            avoid="不要鼓励站队拉踩，也不要把人物写成单纯受害者。",
            lane_affinity=("人情债", "关系困局"),
            scene_keywords=("人情", "亏欠", "关系", "李寻欢", "古龙", "体面", "拒绝"),
            base_priority=6,
        ),
    ),
)


AI_TECH_PACK = TopicPack(
    playbook_id="ai_tech_daily_post",
    default_account_id="acct-ai-tech-local",
    default_image_style="note_card",
    guidance_message="这条 AI 科技资讯建议先从下面选一个普通人能理解的判断框架，再进入生成。",
    lanes=(
        TopicLane(
            name="模型更新 / 3 秒人话",
            default_scene="Google 发布 Gemini 3，想写普通人能懂的 AI 工具变化",
            default_content_angle="先讲具体更新，再把术语翻译成普通人能判断的变化。",
            default_saveable_tool="是什么 / 为什么重要 / 普通人先看什么",
            default_comment_prompt="这次更新你最想先试哪一类任务？",
            keywords=("模型", "Gemini", "ChatGPT", "Claude", "发布", "升级", "更新", "大模型"),
        ),
        TopicLane(
            name="工作流 / 普通人实用",
            default_scene="想写一个 AI 帮普通打工人省下重复劳动的工作流",
            default_content_angle="从一个真实任务写起，判断 AI 能省哪一步，不能替哪一步。",
            default_saveable_tool="任务 / AI 能帮的部分 / 人要把关的部分",
            default_comment_prompt="你最想把哪一步交给 AI 先试？",
            keywords=("工作流", "效率", "办公", "打工人", "工具", "自动化", "文档"),
        ),
        TopicLane(
            name="工具选择 / 避坑判断",
            default_scene="想比较两个 AI 工具，帮读者判断该不该换",
            default_content_angle="不做通稿，给读者一个什么时候用、什么时候不用的选择框架。",
            default_saveable_tool="适合谁 / 不适合谁 / 先试一个任务",
            default_comment_prompt="你现在最纠结哪两个 AI 工具？",
            keywords=("工具", "对比", "选择", "避坑", "适合", "不适合", "换工具"),
        ),
        TopicLane(
            name="普通人影响 / 边界感",
            default_scene="想写 AI 新功能对普通人的影响，但不夸张预测",
            default_content_angle="把行业新闻落到学习、工作、内容生产里的可见影响和边界。",
            default_saveable_tool="会影响什么 / 暂时不影响什么 / 一句判断",
            default_comment_prompt="你更期待 AI 帮忙，还是更担心边界？",
            keywords=("普通人", "影响", "学习", "内容生产", "边界", "担心", "趋势"),
        ),
    ),
    directions=(
        TopicDirection(
            id="ai_model_update_plain_language",
            name="模型更新：3 秒讲清这次变了什么",
            trend_signal="大模型更新 / 科技热点",
            viral_hook="一眼判断卡",
            why_it_may_work="模型更新容易信息过载，三段式人话拆解能帮普通读者迅速判断要不要关注。",
            best_scenes=("新模型发布", "功能升级", "多模态能力变化"),
            content_angle="别先背参数，先看这次更新到底让哪类任务更省事。",
            saveable_tool="是什么 / 为什么重要 / 普通人先看什么",
            comment_prompt="这次更新你最想先试哪一类任务？",
            avoid="不要写成发布会通稿，不要做投资建议或确定性预测。",
            lane_affinity=("模型更新", "3 秒"),
            scene_keywords=("模型", "Gemini", "ChatGPT", "Claude", "发布", "升级", "更新", "大模型"),
            base_priority=8,
        ),
        TopicDirection(
            id="ai_workflow_real_use",
            name="普通人 AI 工作流：先省一个重复步骤",
            trend_signal="AI 工作流 / 打工人效率",
            viral_hook="可保存清单",
            why_it_may_work="把 AI 从抽象热点落到一个任务清单，读者能收藏后直接试一遍。",
            best_scenes=("整理会议纪要", "把资料变成大纲", "批量改写一组文案"),
            content_angle="AI 最适合先帮你省重复步骤，不适合替你做最后判断。",
            saveable_tool="任务 / AI 能帮的部分 / 人要把关的部分",
            comment_prompt="你最想把哪一步交给 AI 先试？",
            avoid="不要承诺效率翻倍，不要把工具写成万能替身。",
            lane_affinity=("工作流",),
            scene_keywords=("工作流", "效率", "办公", "打工人", "工具", "自动化", "文档"),
            base_priority=7,
        ),
        TopicDirection(
            id="ai_tool_comparison_decision",
            name="AI 工具选择：该换、不该换、先试什么",
            trend_signal="工具对比 / 避坑",
            viral_hook="选择框架",
            why_it_may_work="工具选择是高搜索需求，明确适用场景能避免通稿式种草。",
            best_scenes=("两个 AI 工具功能相近", "新功能很热但不确定要不要付费", "旧工作流已经够用"),
            content_angle="判断一个工具值不值得换，不看热闹，看它能不能稳定解决你的一个任务。",
            saveable_tool="适合谁 / 不适合谁 / 先试一个任务",
            comment_prompt="你现在最纠结哪两个 AI 工具？",
            avoid="不要做夸张带货，不要暗示购买后一定提升。",
            lane_affinity=("工具选择",),
            scene_keywords=("工具", "对比", "选择", "避坑", "适合", "不适合", "付费"),
            base_priority=6,
        ),
        TopicDirection(
            id="ai_ordinary_person_impact",
            name="普通人影响：这次 AI 热点和你有什么关系",
            trend_signal="普通人影响 / AI 生活搭子",
            viral_hook="评论区用法",
            why_it_may_work="普通人影响比行业宏大叙事更容易被转发，也能自然讨论工具边界。",
            best_scenes=("AI 新功能进入手机或办公软件", "学习方式被改变", "内容生产门槛变化"),
            content_angle="不是所有 AI 新闻都要立刻追，但有些变化会悄悄改掉你的默认工作流。",
            saveable_tool="会影响什么 / 暂时不影响什么 / 一句判断",
            comment_prompt="你更期待 AI 帮忙，还是更担心边界？",
            avoid="不要制造失业恐慌，不要写成暴富或投资机会。",
            lane_affinity=("普通人影响",),
            scene_keywords=("普通人", "影响", "学习", "内容生产", "边界", "担心", "趋势"),
            base_priority=6,
        ),
    ),
)


DAILY_ENGLISH_PACK = TopicPack(
    playbook_id="daily_english_post",
    default_account_id="acct-daily-english-local",
    default_image_style="note_card",
    guidance_message="这条每日英语内容建议先从下面选一个明天能用的表达场景，再进入生成。",
    lanes=(
        TopicLane(
            name="职场表达 / 可复制句型",
            default_scene="学一个表示坚持的高级词汇，想配真实职场例句",
            default_content_angle="用真实工作场景带出表达，给读者一个可替换句型。",
            default_saveable_tool="单词 / 职场例句 / 可替换句型",
            default_comment_prompt="你想用这个表达造一个什么职场句？",
            keywords=("职场", "会议", "邮件", "坚持", "表达", "例句", "高级词汇"),
        ),
        TopicLane(
            name="情绪词 / 场景记忆",
            default_scene="想学一个能表达心累但不夸张的英文词",
            default_content_angle="把情绪词放进真实生活语境，避免词典式解释。",
            default_saveable_tool="情绪词 / 使用场景 / 别这样误用",
            default_comment_prompt="你今天最想表达哪一种情绪？",
            keywords=("情绪", "心累", "焦虑", "开心", "沮丧", "压力", "表达"),
        ),
        TopicLane(
            name="每日一词 / 学习陪伴",
            default_scene="今天只学一个明天聊天就能用的高频词",
            default_content_angle="保持轻量陪伴感，让读者学完能马上用一句。",
            default_saveable_tool="音标 / 词性 / 例句 / 替换模板",
            default_comment_prompt="你用今天这个词造一句，我帮你顺一下。",
            keywords=("每日", "单词", "短语", "高频", "明天", "聊天", "学习"),
        ),
        TopicLane(
            name="评论区造句 / 互动练习",
            default_scene="想做一条评论区可以一起造句的英语表达",
            default_content_angle="把练习设计成低压力互动，不像课堂作业。",
            default_saveable_tool="表达 / 你的例句 / 可以替换的部分",
            default_comment_prompt="把你的句子留在评论区，我帮你改得更自然。",
            keywords=("评论区", "造句", "练习", "改句子", "互动", "自然", "替换"),
        ),
    ),
    directions=(
        TopicDirection(
            id="english_workplace_phrase",
            name="职场表达：一个明天能用的句型",
            trend_signal="职场英语 / 可复制句型",
            viral_hook="收藏模板",
            why_it_may_work="职场表达有明确使用场景，读者能直接把句型替换到会议、邮件或汇报里。",
            best_scenes=("会议里表达坚持", "邮件里委婉推进", "汇报里说明进展"),
            content_angle="不是背一个高级词，而是学一句你明天真的能说出口的话。",
            saveable_tool="单词 / 职场例句 / 可替换句型",
            comment_prompt="你想用这个表达造一个什么职场句？",
            avoid="不要写成词典释义，不要用不自然的中式英文例句。",
            lane_affinity=("职场表达",),
            scene_keywords=("职场", "会议", "邮件", "坚持", "表达", "例句", "高级词汇"),
            base_priority=8,
        ),
        TopicDirection(
            id="english_emotion_word",
            name="情绪词：把心情说得更准确一点",
            trend_signal="情绪表达 / 生活英语",
            viral_hook="评论区交情绪",
            why_it_may_work="情绪词容易有代入感，真实场景例句能让读者感觉学了就能用。",
            best_scenes=("想说心累但不想太dramatic", "表达压力", "聊天里说今天有点撑不住"),
            content_angle="会说情绪，不是为了显得高级，是为了把自己的状态说清楚一点。",
            saveable_tool="情绪词 / 使用场景 / 别这样误用",
            comment_prompt="你今天最想表达哪一种情绪？",
            avoid="不要把情绪表达写成心理诊断，不要堆同义词。",
            lane_affinity=("情绪词",),
            scene_keywords=("情绪", "心累", "焦虑", "开心", "沮丧", "压力", "状态"),
            base_priority=7,
        ),
        TopicDirection(
            id="english_one_word_today",
            name="每日一词：轻量学习搭子",
            trend_signal="每日学习 / 陪伴感",
            viral_hook="打卡但不鸡血",
            why_it_may_work="固定栏目降低阅读压力，轻量例句比完整课程更适合小红书日更。",
            best_scenes=("今天只学一个高频词", "想保持英语手感", "想把热词落成自然英文"),
            content_angle="今天不贪多，只把一个表达学到明天能用。",
            saveable_tool="音标 / 词性 / 例句 / 替换模板",
            comment_prompt="你用今天这个词造一句，我帮你顺一下。",
            avoid="不要写成课堂打卡模板，不要用生僻词制造学习负担。",
            lane_affinity=("每日一词",),
            scene_keywords=("每日", "单词", "短语", "高频", "明天", "聊天", "学习"),
            base_priority=6,
        ),
        TopicDirection(
            id="english_comment_sentence",
            name="评论区造句：把练习变轻一点",
            trend_signal="互动练习 / 评论区共创",
            viral_hook="评论区改句子",
            why_it_may_work="低压力造句能把收藏转成评论互动，也能让读者感觉账号真的在陪练。",
            best_scenes=("学完短语后造句", "读者想知道这样说自然不自然", "把一个中文场景换成英文"),
            content_angle="练英语可以不用像交作业，先留一句，我们一起改得自然一点。",
            saveable_tool="表达 / 你的例句 / 可以替换的部分",
            comment_prompt="把你的句子留在评论区，我帮你改得更自然。",
            avoid="不要用老师批改口吻，不要让读者觉得被考试。",
            lane_affinity=("评论区造句",),
            scene_keywords=("评论区", "造句", "练习", "改句子", "互动", "自然", "替换"),
            base_priority=6,
        ),
    ),
)


WORLD_CUP_PACK = TopicPack(
    playbook_id="world_cup_daily_post",
    default_account_id="acct-world-cup-local",
    default_image_style="note_card",
    guidance_message="这条世界杯内容建议先从下面选一个普通球迷能参与的看球入口，再进入生成。",
    lanes=(
        TopicLane(
            name="看球清单 / 可保存",
            default_scene="阿根廷和法国决赛前，想写普通球迷看球清单",
            default_content_angle="把比赛写成普通球迷能边看边用的观察清单。",
            default_saveable_tool="比赛语境 / 2-3 个看点 / 看球清单",
            default_comment_prompt="你今晚最想看哪一个对位？",
            keywords=("看球", "清单", "决赛", "赛前", "阿根廷", "法国", "普通球迷"),
        ),
        TopicLane(
            name="球迷情绪 / 看球搭子",
            default_scene="想写一条熬夜看球前的球迷情绪笔记",
            default_content_angle="先写普通球迷的期待、紧张和氛围，再给可聊的看点。",
            default_saveable_tool="情绪入口 / 看点 / 评论区站队",
            default_comment_prompt="你看球时最容易在哪一秒屏住呼吸？",
            keywords=("球迷", "熬夜", "紧张", "期待", "氛围", "搭子", "站队"),
        ),
        TopicLane(
            name="赛前看点 / 人话拆解",
            default_scene="想写一场比赛赛前 3 个普通人能看懂的看点",
            default_content_angle="不装专家，只把战术讲到普通球迷能一起看的层级。",
            default_saveable_tool="看点 / 怎么看 / 聊天话题",
            default_comment_prompt="你最想看哪组对位？",
            keywords=("赛前", "看点", "对位", "边路", "中场", "定位球", "逼抢"),
        ),
        TopicLane(
            name="赛后复盘 / 不预测",
            default_scene="赛后想写一条不装专家的普通球迷复盘",
            default_content_angle="按情绪、关键瞬间和可复盘看点收束，不做确定性预测。",
            default_saveable_tool="关键瞬间 / 普通球迷看法 / 下次看什么",
            default_comment_prompt="这场球你最想复盘哪一个瞬间？",
            keywords=("赛后", "复盘", "关键瞬间", "遗憾", "点球", "加时", "下半场"),
        ),
    ),
    directions=(
        TopicDirection(
            id="worldcup_match_watching_checklist",
            name="看球清单：普通球迷也能一起看",
            trend_signal="看球搭子 / 可保存清单",
            viral_hook="收藏看球卡",
            why_it_may_work="清单形式降低专业门槛，适合赛前收藏、赛中对照和评论区一起补充。",
            best_scenes=("决赛赛前", "淘汰赛焦点战", "朋友一起看球前"),
            content_angle="今晚不用装懂球，先带着这 3 个问题看就够了。",
            saveable_tool="比赛语境 / 2-3 个看点 / 看球清单",
            comment_prompt="你今晚最想看哪一个对位？",
            avoid="不要写赌球、盘口、下注建议、确定性比分预测或内部消息。",
            lane_affinity=("看球清单",),
            scene_keywords=("看球", "清单", "决赛", "赛前", "阿根廷", "法国", "普通球迷"),
            base_priority=8,
        ),
        TopicDirection(
            id="worldcup_fan_emotion_note",
            name="球迷情绪：熬夜前那一点紧张",
            trend_signal="球迷情绪 / 氛围感",
            viral_hook="评论区站队",
            why_it_may_work="情绪入口比专业赛报更有参与感，能让轻度球迷也愿意评论。",
            best_scenes=("熬夜看球", "朋友约球局", "点球前屏住呼吸"),
            content_angle="世界杯最动人的不只是比分，还有一群人同时紧张的那几分钟。",
            saveable_tool="情绪入口 / 看点 / 评论区站队",
            comment_prompt="你看球时最容易在哪一秒屏住呼吸？",
            avoid="不要拉踩球队或球迷，不要制造饭圈对立。",
            lane_affinity=("球迷情绪",),
            scene_keywords=("球迷", "熬夜", "紧张", "期待", "氛围", "搭子", "站队"),
            base_priority=7,
        ),
        TopicDirection(
            id="worldcup_plain_preview",
            name="赛前看点：把战术讲成人话",
            trend_signal="赛前看点 / 人话拆解",
            viral_hook="2-3 个看点",
            why_it_may_work="赛前内容有强搜索入口，人话拆解能避免普通读者被专业术语挡住。",
            best_scenes=("赛前 2 小时", "强强对话", "普通球迷想知道看什么"),
            content_angle="这场不用背术语，先看中场节奏、边路空间和定位球这几件事。",
            saveable_tool="看点 / 怎么看 / 聊天话题",
            comment_prompt="你最想看哪组对位？",
            avoid="不要把未确认的首发、伤病或赛程写成事实。",
            lane_affinity=("赛前看点",),
            scene_keywords=("赛前", "看点", "对位", "边路", "中场", "定位球", "逼抢"),
            base_priority=7,
        ),
        TopicDirection(
            id="worldcup_post_match_reframe",
            name="赛后复盘：先收住情绪，再看三个瞬间",
            trend_signal="赛后复盘 / 普通球迷视角",
            viral_hook="复盘顺序",
            why_it_may_work="赛后情绪强，给一个复盘顺序能把争吵转成可讨论的关键瞬间。",
            best_scenes=("赛后很遗憾", "点球大战结束", "想讨论但不想吵架"),
            content_angle="赛后不是马上找战犯，先把真正改变比赛的几个瞬间看清楚。",
            saveable_tool="关键瞬间 / 普通球迷看法 / 下次看什么",
            comment_prompt="这场球你最想复盘哪一个瞬间？",
            avoid="不要写确定性预测，不要冒充官方消息或内部消息。",
            lane_affinity=("赛后复盘",),
            scene_keywords=("赛后", "复盘", "关键瞬间", "遗憾", "点球", "加时", "下半场"),
            base_priority=6,
        ),
    ),
)


REDDIT_CURATION_PACK = TopicPack(
    playbook_id="reddit_curation_daily_post",
    default_account_id="acct-reddit-curation-local",
    default_image_style="note_card",
    guidance_message="这条外网讨论转译内容建议先从下面选一个适合中文读者的热点观察角度，再进入生成。",
    lanes=(
        TopicLane(
            name="AI 工具焦虑 / 中文语境",
            default_scene="从外网 AI 工具焦虑讨论里选一个适合中文读者的角度",
            default_content_angle="把英文社区现象消化成中文读者能共鸣的 AI 使用压力。",
            default_saveable_tool="现象 / 核心判断 / 可收藏小结",
            default_comment_prompt="你现在更像是在用 AI，还是在照看 AI？",
            keywords=("外网", "AI", "工具", "焦虑", "中文读者", "讨论", "压力"),
        ),
        TopicLane(
            name="效率工作流 / 经验转译",
            default_scene="想把海外用户的效率工具经验写成中文读者可用的小结",
            default_content_angle="不搬运个案，只提炼一个中文读者能试的工作流判断。",
            default_saveable_tool="场景 / 做法 / 适合先试的人",
            default_comment_prompt="你最想优化哪一步工作流？",
            keywords=("效率", "工作流", "经验", "工具", "productivity", "方法", "小结"),
        ),
        TopicLane(
            name="生活压力 / 非诊断观察",
            default_scene="想写一种大家都在被消息和工具追着跑的生活压力",
            default_content_angle="把生活压力写成普通人的观察，不诊断、不承诺治愈。",
            default_saveable_tool="压力来源 / 共鸣点 / 今天能停在哪一步",
            default_comment_prompt="你最近最想先停下哪一个信息入口？",
            keywords=("生活", "压力", "消息", "注意力", "心理", "情绪", "停不下来"),
        ),
        TopicLane(
            name="中文读者角度 / 为什么值得关心",
            default_scene="想写一个外网热点为什么会让中文读者也有感觉",
            default_content_angle="先解释这个现象为什么值得中文读者关心，再给一条可讨论判断。",
            default_saveable_tool="现象 / 为什么有关 / 你可以怎么判断",
            default_comment_prompt="这个现象让你想到自己哪一个场景？",
            keywords=("中文读者", "热点", "现象", "为什么", "共鸣", "观察", "判断"),
        ),
    ),
    directions=(
        TopicDirection(
            id="reddit_ai_tool_anxiety",
            name="AI 工具焦虑：到底是谁在被谁训练",
            trend_signal="AI 工具焦虑 / 普通人压力",
            viral_hook="一句判断引评论",
            why_it_may_work="AI 工具焦虑是跨平台共鸣点，中文读者也容易代入被工具节奏追着跑的感受。",
            best_scenes=("工具越装越多", "为了效率反而更累", "不知道该不该跟新模型"),
            content_angle="很多人不是不会用 AI，而是开始觉得自己每天都在照看一堆工具。",
            saveable_tool="现象 / 核心判断 / 可收藏小结",
            comment_prompt="你现在更像是在用 AI，还是在照看 AI？",
            avoid="不要展示平台名、用户身份、链接或翻译过程，不要做投资建议。",
            lane_affinity=("AI 工具焦虑",),
            scene_keywords=("外网", "AI", "工具", "焦虑", "中文读者", "讨论", "压力"),
            base_priority=8,
        ),
        TopicDirection(
            id="reddit_workflow_case",
            name="效率工作流：一个能先试的小改法",
            trend_signal="效率工具 / 工作流经验",
            viral_hook="可保存小结",
            why_it_may_work="把经验转成可试步骤，比搬运讨论更适合小红书收藏。",
            best_scenes=("整理资料太散", "AI 工具接不上旧流程", "想用一个小改法省重复劳动"),
            content_angle="真正有用的工作流，不是工具越多越好，而是少一个反复切换的动作。",
            saveable_tool="场景 / 做法 / 适合先试的人",
            comment_prompt="你最想优化哪一步工作流？",
            avoid="不要把别人的经历写成作者亲历，不要复制长段英文原文。",
            lane_affinity=("效率工作流",),
            scene_keywords=("效率", "工作流", "经验", "工具", "productivity", "方法", "小结"),
            base_priority=7,
        ),
        TopicDirection(
            id="reddit_psych_life_pressure",
            name="生活压力观察：消息和工具都在追人",
            trend_signal="注意力压力 / 非诊断观察",
            viral_hook="评论区共鸣",
            why_it_may_work="消息压力和工具压力是普遍体验，非诊断化表达能兼顾共鸣与安全边界。",
            best_scenes=("消息回不完", "工具提醒太多", "想提高效率却越来越碎"),
            content_angle="有时让人累的不是某一个任务，而是每个入口都在说快一点。",
            saveable_tool="压力来源 / 共鸣点 / 今天能停在哪一步",
            comment_prompt="你最近最想先停下哪一个信息入口？",
            avoid="不要做心理诊断，不要承诺治愈，不要建议用药。",
            lane_affinity=("生活压力",),
            scene_keywords=("生活", "压力", "消息", "注意力", "心理", "情绪", "停不下来"),
            base_priority=6,
        ),
        TopicDirection(
            id="reddit_chinese_reader_angle",
            name="中文读者为什么也会关心这个热点",
            trend_signal="热点观察 / 中文语境",
            viral_hook="关系到我吗",
            why_it_may_work="先回答为什么有关，能把外部讨论转成中文读者愿意停下来的判断。",
            best_scenes=("外部热点很热但离读者有距离", "AI 或效率议题需要本地化理解", "想写成中文语境观察"),
            content_angle="一个热点值不值得看，关键不是它有多热，而是它改变了普通人的哪个默认动作。",
            saveable_tool="现象 / 为什么有关 / 你可以怎么判断",
            comment_prompt="这个现象让你想到自己哪一个场景？",
            avoid="不要展示采集过程、原始讨论位置、链接或账号身份。",
            lane_affinity=("中文读者角度",),
            scene_keywords=("中文读者", "热点", "现象", "为什么", "共鸣", "观察", "判断"),
            base_priority=6,
        ),
    ),
)


TOPIC_GUIDANCE_PACKS = {
    FENGKUANG_PACK.playbook_id: FENGKUANG_PACK,
    HUMAN_ENRICHMENT_PACK.playbook_id: HUMAN_ENRICHMENT_PACK,
    SUSHI_POETRY_PACK.playbook_id: SUSHI_POETRY_PACK,
    WUXIA_CHARACTER_PACK.playbook_id: WUXIA_CHARACTER_PACK,
    AI_TECH_PACK.playbook_id: AI_TECH_PACK,
    DAILY_ENGLISH_PACK.playbook_id: DAILY_ENGLISH_PACK,
    WORLD_CUP_PACK.playbook_id: WORLD_CUP_PACK,
    REDDIT_CURATION_PACK.playbook_id: REDDIT_CURATION_PACK,
}

DEFAULT_ACCOUNT_BY_PLAYBOOK = {
    playbook_id: pack.default_account_id
    for playbook_id, pack in TOPIC_GUIDANCE_PACKS.items()
}
