from __future__ import annotations

from ptsm.domain.topic_guidance import TopicDirection, TopicLane, TopicPack


FENGKUANG_PACK = TopicPack(
    playbook_id="fengkuang_daily_post",
    default_account_id="acct-fk-local",
    default_image_style="note_card",
    guidance_message="这条发疯文学内容建议先从下面选一个可接龙方向，再进入生成。",
    lanes=(
        TopicLane(
            name="职场物件 / 替人发疯",
            default_scene="领导18:57发来一句在吗，工牌想替我发疯",
            default_content_angle="让一个具体物件替打工人说出没发出去的疯话。",
            default_saveable_tool="物件 / 疯话 / 体面翻译三栏",
            default_comment_prompt="你今天想让哪个物件替你发疯？",
            keywords=("工牌", "电脑", "键盘", "杯子", "领导", "工位", "物件"),
        ),
        TopicLane(
            name="高雅外壳 / 狼狈内核",
            default_scene="明明只是被临时加活，却想写成一碗丝瓜汤",
            default_content_angle="用体面词包装狼狈现场，让反差成为笑点。",
            default_saveable_tool="原句 / 高雅说法 / 实际意思",
            default_comment_prompt="你还有什么高雅外壳的狼狈句？",
            keywords=("高雅", "狼狈", "丝瓜汤", "体面", "翻译"),
        ),
        TopicLane(
            name="群聊未发送 / 评论区接龙",
            default_scene="群聊里那句没发出去的话，最后让评论区替我说了",
            default_content_angle="把没发出去的一句话变成评论区接龙入口。",
            default_saveable_tool="场景 / 没发出去的话 / 体面版本",
            default_comment_prompt="把你没发出去的那句话留在评论区。",
            keywords=("群聊", "没发", "回复", "接龙", "消息", "在吗"),
        ),
        TopicLane(
            name="体面人设 / 活人崩溃",
            default_scene="表面收到，实际灵魂已经从会议室离职",
            default_content_angle="表面维持体面，内核保留活人的荒诞反应。",
            default_saveable_tool="表面台词 / 内心字幕 / 今日缓冲词",
            default_comment_prompt="你今天哪一秒最像体面外壳裂开？",
            keywords=("体面", "收到", "会议", "崩溃", "活人", "下班"),
        ),
    ),
    directions=(
        TopicDirection(
            id="fk_work_object_vent",
            name="职场物件替人发疯",
            trend_signal="物件发疯 / 抽象力",
            viral_hook="评论区补一句",
            why_it_may_work="把情绪交给工牌、键盘、杯子这类具体物件，既有代入感，也方便评论区接力。",
            best_scenes=("领导临下班发在吗", "工牌像替身一样挂了一天", "电脑风扇比人先崩溃"),
            content_angle="不是人在发疯，是工牌终于替我把那句话说出来了。",
            saveable_tool="物件 / 它想说的话 / 体面翻译",
            comment_prompt="你今天想让哪个物件替你发疯？",
            avoid="不要拿心理疾病、医院、治疗或用药当笑点。",
            lane_affinity=("职场物件",),
            scene_keywords=("工牌", "键盘", "电脑", "杯子", "领导", "工位", "发疯"),
            base_priority=8,
        ),
        TopicDirection(
            id="fk_loofah_soup_reply",
            name="丝瓜汤式复盘",
            trend_signal="丝瓜汤 / 高雅外壳",
            viral_hook="可复制疯话",
            why_it_may_work="用高雅句式包住真实狼狈，反差强，也能让用户贡献自己的体面翻译。",
            best_scenes=("被安排临时需求", "一句收到背后有很多话", "想把崩溃写得很讲究"),
            content_angle="把不想干写成一碗温润的丝瓜汤，体面但不失真。",
            saveable_tool="原句 / 丝瓜汤说法 / 实际意思",
            comment_prompt="你还有哪句适合熬成丝瓜汤？",
            avoid="不要攻击具体个人，不要变成阴阳怪气人身攻击。",
            lane_affinity=("高雅外壳",),
            scene_keywords=("丝瓜汤", "高雅", "体面", "临时", "收到", "复盘"),
            base_priority=7,
        ),
        TopicDirection(
            id="fk_group_chat_unsent_line",
            name="群聊没发出去的话",
            trend_signal="打工人关系角色",
            viral_hook="接龙",
            why_it_may_work="未发送消息是高频场景，评论区天然会接自己的那一句。",
            best_scenes=("群聊里忍住没回", "领导发在吗", "同事让你帮忙兜底"),
            content_angle="最疯的不是发出去的话，是删掉以后还在脑子里加班的那句。",
            saveable_tool="场景 / 没发出去的话 / 体面版本",
            comment_prompt="把你没发出去的那句话交出来。",
            avoid="不要鼓励网暴、挂人或泄露真实聊天隐私。",
            lane_affinity=("群聊未发送",),
            scene_keywords=("群聊", "没发", "没发出去", "在吗", "消息", "回复", "领导"),
            base_priority=7,
        ),
        TopicDirection(
            id="fk_polite_shell_wild_core",
            name="体面外壳狼狈内核",
            trend_signal="高雅外壳 / 活人感",
            viral_hook="身份认领",
            why_it_may_work="体面与狼狈的反差容易被认领，也能保持发疯文学的分寸。",
            best_scenes=("表面说收到", "会后还在脑内骂骂咧咧", "下班路上突然想通又没想通"),
            content_angle="体面是外壳，活人才是内核。",
            saveable_tool="表面台词 / 内心字幕 / 今日缓冲词",
            comment_prompt="你今天是哪一种体面外壳？",
            avoid="不要把崩溃写成伤害自己或他人的行动建议。",
            lane_affinity=("体面人设", "高雅外壳"),
            scene_keywords=("体面", "收到", "狼狈", "活人", "崩溃", "下班"),
            base_priority=6,
        ),
    ),
)


HUMAN_ENRICHMENT_PACK = TopicPack(
    playbook_id="human_enrichment_daily_post",
    default_account_id="acct-enrichment-local",
    default_image_style="note_card",
    guidance_message="这条人类丰容内容建议先从下面选一个低成本变量方向，再进入生成。",
    lanes=(
        TopicLane(
            name="一平米角落 / 低成本变量",
            default_scene="把书桌角落改成十分钟适我主义手作位",
            default_content_angle="不是改造整个家，只给一个角落加一个下班信号。",
            default_saveable_tool="原本惯性 / 一个变量 / 今天能试的一步",
            default_comment_prompt="你先想丰容哪个角落？",
            keywords=("书桌", "角落", "工位", "床头", "玄关", "适我主义"),
        ),
        TopicLane(
            name="睡前下线 / 微仪式",
            default_scene="床头只放充电线，睡前总觉得没下线",
            default_content_angle="给睡前十分钟加一个可重复的结束信号。",
            default_saveable_tool="入口 / 下线动作 / 明天第一步",
            default_comment_prompt="你想先给哪个入口下线？",
            keywords=("床头", "睡前", "下线", "十分钟", "充电线"),
        ),
        TopicLane(
            name="通勤路线 / Colorwalk",
            default_scene="下班路上给自己一个找绿色的任务",
            default_content_angle="不换城市，只给通勤路线加一个感官变量。",
            default_saveable_tool="路线 / 颜色任务 / 拍到的一处细节",
            default_comment_prompt="你会给通勤加什么颜色任务？",
            keywords=("通勤", "路线", "colorwalk", "颜色", "下班路"),
        ),
        TopicLane(
            name="手作材料 / 心流平铺",
            default_scene="把手作材料摊开，先做十分钟就停",
            default_content_angle="材料平铺比成品更容易展示今天能开始的一步。",
            default_saveable_tool="材料 / 十分钟动作 / 停止点",
            default_comment_prompt="你最想摊开哪一种材料？",
            keywords=("手作", "材料", "心流", "平铺", "十分钟"),
        ),
    ),
    directions=(
        TopicDirection(
            id="enrichment_desk_corner_variable",
            name="一平米角落：书桌下班信号",
            trend_signal="适我主义 / 新独居",
            viral_hook="低成本 before/after",
            why_it_may_work="具体角落加三步清单容易收藏，也容易让评论区交作业。",
            best_scenes=("书桌太像工位", "床头只有充电线", "玄关一进门就很乱"),
            content_angle="不是改造整个家，只是给一个角落加一个下班信号。",
            saveable_tool="原本惯性 / 一个变量 / 今天能试的一步",
            comment_prompt="你先想丰容哪个角落？",
            avoid="不要写成购物清单，不要用 AI 图伪装真实改造。",
            lane_affinity=("一平米角落",),
            scene_keywords=("书桌", "角落", "工位", "适我主义", "低成本"),
            base_priority=8,
        ),
        TopicDirection(
            id="enrichment_bedside_shutdown_signal",
            name="床头下线信号",
            trend_signal="睡前十分钟",
            viral_hook="三步清单",
            why_it_may_work="睡前场景高频，三步下线动作比宏大自律更容易被保存。",
            best_scenes=("床头只有充电线", "睡前刷手机停不下来", "想让房间有结束感"),
            content_angle="丰容不是多买东西，是让身体知道今天可以结束了。",
            saveable_tool="关入口 / 留明天第一步 / 放一个低刺激物件",
            comment_prompt="你想给睡前加哪一个下线信号？",
            avoid="不要做助眠治疗承诺，不要把失眠简单归因于自控力。",
            lane_affinity=("睡前下线",),
            scene_keywords=("床头", "睡前", "下线", "充电线", "十分钟"),
            base_priority=7,
        ),
        TopicDirection(
            id="enrichment_route_colorwalk",
            name="通勤路线微变量",
            trend_signal="Colorwalk / 低成本行动",
            viral_hook="交作业",
            why_it_may_work="路线变量不需要购物，评论区可以用颜色任务交作业。",
            best_scenes=("每天同一条下班路", "周末不想远行", "想低成本找回一点新鲜感"),
            content_angle="不换城市，也能把今天的路线换一个观察方式。",
            saveable_tool="路线 / 颜色 / 一张细节照片",
            comment_prompt="你明天的通勤颜色任务是什么？",
            avoid="不要写成旅游攻略，也不要暗示危险拍摄或影响通行。",
            lane_affinity=("通勤路线",),
            scene_keywords=("通勤", "路线", "colorwalk", "颜色", "下班路"),
            base_priority=6,
        ),
        TopicDirection(
            id="enrichment_handmade_material_flow",
            name="手作材料平铺",
            trend_signal="手作心流",
            viral_hook="过程轮播",
            why_it_may_work="材料和过程比完美成品更有真实感，也适合轮播拆步骤。",
            best_scenes=("想做手作但迟迟没开始", "材料堆在角落", "只想做十分钟"),
            content_angle="今天不追求完成，只把材料摊开，让开始变小。",
            saveable_tool="材料 / 十分钟动作 / 停止点",
            comment_prompt="你最想摊开哪一种材料？",
            avoid="不要写成昂贵工具种草，不要把失败手作包装成完美教程。",
            lane_affinity=("手作材料",),
            scene_keywords=("手作", "材料", "心流", "平铺", "十分钟"),
            base_priority=6,
        ),
    ),
)


SUSHI_POETRY_PACK = TopicPack(
    playbook_id="sushi_poetry_daily_post",
    default_account_id="acct-sushi-local",
    default_image_style="note_card",
    guidance_message="这条苏轼诗词内容建议先从下面选一个当代生活入口，再进入生成。",
    lanes=(
        TopicLane(
            name="怀民关系 / 角色认领",
            default_scene="夜里读到怀民亦未寝，想写一种旧友关系",
            default_content_angle="从一句词落回当代人想找一个旧友说话的瞬间。",
            default_saveable_tool="词句 / 当代瞬间 / 可保存小纸条",
            default_comment_prompt="你是会叫怀民的人，还是会被叫起来的人？",
            keywords=("怀民", "旧友", "朋友", "夜里", "未寝"),
        ),
        TopicLane(
            name="旧物旧友 / 精神充电",
            default_scene="翻到一件旧物，突然想起一个老朋友",
            default_content_angle="用旧物作为入口，把诗词写成一次温和的精神充电。",
            default_saveable_tool="旧物 / 词句 / 今天能写的一句",
            default_comment_prompt="你会把哪件旧物交给苏轼？",
            keywords=("旧物", "旧友", "老朋友", "精神", "充电"),
        ),
        TopicLane(
            name="节气小动作 / 生活仪式",
            default_scene="一个节气里只做一件小事",
            default_content_angle="把节气从知识点写成今天能做的小动作。",
            default_saveable_tool="节气 / 一件小事 / 一句词",
            default_comment_prompt="这个节气你想做哪件小事？",
            keywords=("节气", "非遗", "季节", "小动作", "仪式"),
        ),
        TopicLane(
            name="坏天气 / 定风波重读",
            default_scene="今天过得很狼狈，想借定风波重新看一眼",
            default_content_angle="不把狼狈美化，只借苏轼给它一个可放下的句子。",
            default_saveable_tool="狼狈场景 / 词句 / 放下一步",
            default_comment_prompt="你今天最想把哪点狼狈写进一句词？",
            keywords=("定风波", "狼狈", "坏天气", "风雨", "放下"),
        ),
    ),
    directions=(
        TopicDirection(
            id="sushi_role_pair_huimin",
            name="苏轼/怀民关系角色",
            trend_signal="文化力 / 角色认领",
            viral_hook="你是 A 还是 B",
            why_it_may_work="怀民是天然评论入口，读者容易认领自己是叫人的人还是被叫起来的人。",
            best_scenes=("夜里想找旧友说话", "朋友一句普通回复让人缓过来", "读到怀民亦未寝"),
            content_angle="不是只有宏大的友情，半夜有人知道你还醒着也很珍贵。",
            saveable_tool="词句 / 当代瞬间 / 可保存小纸条",
            comment_prompt="你是会叫怀民的人，还是会被叫起来的人？",
            avoid="不要写成百科讲义，不要过度神化古人关系。",
            lane_affinity=("怀民关系",),
            scene_keywords=("怀民", "未寝", "旧友", "朋友", "夜里", "关系"),
            base_priority=8,
        ),
        TopicDirection(
            id="sushi_old_friend_note",
            name="旧友旧物里的精神充电",
            trend_signal="旧物 / 活人感",
            viral_hook="评论交一个人",
            why_it_may_work="旧物和旧友能把诗词从知识点变成普通人的记忆入口。",
            best_scenes=("翻到旧照片", "想起一个很久没联系的人", "被一件小物件安慰"),
            content_angle="旧物不是怀旧滤镜，是提醒你曾经被认真陪过。",
            saveable_tool="旧物 / 词句 / 今天能写的一句",
            comment_prompt="你想把哪位旧友交给评论区？",
            avoid="不要暴露他人隐私，不要写成伤感煽情长文。",
            lane_affinity=("旧物旧友",),
            scene_keywords=("旧物", "旧友", "老朋友", "照片", "精神", "充电"),
            base_priority=7,
        ),
        TopicDirection(
            id="sushi_season_micro_ritual",
            name="节气里的小动作",
            trend_signal="节气 / 非遗",
            viral_hook="可保存小纸条",
            why_it_may_work="节气话题有搜索入口，小动作能避免百科腔。",
            best_scenes=("立夏想做一件小事", "下雨天泡一杯茶", "季节变化时想慢一点"),
            content_angle="节气不是知识点，是今天可以慢慢做的一件小事。",
            saveable_tool="节气 / 一件小事 / 一句词",
            comment_prompt="这个节气你想做哪件小事？",
            avoid="不要伪造民俗出处，不要把节气写成空泛鸡汤。",
            lane_affinity=("节气小动作",),
            scene_keywords=("节气", "非遗", "季节", "小动作", "仪式"),
            base_priority=6,
        ),
        TopicDirection(
            id="sushi_bad_day_reframe",
            name="把狼狈写进一句词",
            trend_signal="柔软力",
            viral_hook="轻量重读",
            why_it_may_work="坏天气和狼狈感高代入，苏轼词句能给出轻量重读而不是说教。",
            best_scenes=("今天很狼狈", "遇到坏天气", "读到定风波想放过自己"),
            content_angle="不是把狼狈变美，而是给它一个可以暂时放下的句子。",
            saveable_tool="狼狈场景 / 词句 / 放下一步",
            comment_prompt="你今天最想把哪点狼狈写进一句词？",
            avoid="不要用诗词否定现实困难，也不要写成万能治愈。",
            lane_affinity=("坏天气",),
            scene_keywords=("定风波", "狼狈", "风雨", "坏天气", "放下"),
            base_priority=6,
        ),
    ),
)


TOPIC_GUIDANCE_PACKS = {
    FENGKUANG_PACK.playbook_id: FENGKUANG_PACK,
    HUMAN_ENRICHMENT_PACK.playbook_id: HUMAN_ENRICHMENT_PACK,
    SUSHI_POETRY_PACK.playbook_id: SUSHI_POETRY_PACK,
}

DEFAULT_ACCOUNT_BY_PLAYBOOK = {
    playbook_id: pack.default_account_id
    for playbook_id, pack in TOPIC_GUIDANCE_PACKS.items()
}
